### ISSUE TITLE
As a bounty curator, I want to create a child bounty on bounty detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#1899]
1. Show curator on bounties side bar
2. If curator is a multisig address, show multisig details including threshold and signatories

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11159%3A53466&viewport=-1816%2C79%2C0.58&t=qHRcw758SOY1CgsC-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/204986622-5d56d80c-333b-4498-8d96-d1fc93219899.png">

**Comment by wliyongfeng** [comment]
done in #4781
