### ISSUE TITLE
Add dotreasury profile link to profile page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2086]
There should be an interface for users to see the detail treasury activities.

- Only for polkadot and kusama.

@Popoulosss Please add it in figma.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=7138%3A51767)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/196869547-5e3c027e-7614-4c18-b344-b070798aec15.png">
