### ISSUE TITLE
Implement subscription settings and email template for treasury tip

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/subsquare#2104]
- [x] Settings and email template design (@Popoulosss )
- [x] Implement (@hyifeng )

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9418%3A43917)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/198211829-ee64b89a-a694-4a10-97f5-c786763820df.png">

**Comment by Popoulosss** [comment]
- [ ] Subscription settings

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9189%3A44027)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/198212655-eee2c27c-3d3b-4b24-81bf-b1eafb72641a.png">
