### ISSUE TITLE
feat: gov 2

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#2119]
- [x] #2120
- [x] #2138
- [x] #2132
- [x] #2186

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9484%3A43641)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/199382061-5edf2655-243e-460a-91e8-bcb9739c2e31.png">
