### ISSUE TITLE
gov 2 menu switch

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#2120]
- not an env condition

**Comment by 2nthony** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9484%3A43641)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/199382061-5edf2655-243e-460a-91e8-bcb9739c2e31.png">

**Comment by Popoulosss** [comment]
Gov2 referenda track icons

Files
[icons-track.zip](https://github.com/opensquare-network/subsquare/files/9915458/icons-track.zip)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/199383354-2bcd2b6f-e073-4c2f-9024-fa8adc7e9cbb.png">
