### ISSUE TITLE
Implement Gov2 backend API

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/subsquare#2129]
- [x] Add track list
- [x] Referendum/Track summary
- [x] Get referendum post list by track ID/Name
  - [x] Implement post state sync script to sync the last activate time of the post (Timeline and reply)
  - [x] Implement post list API with correct sort
- [x] Get referendum post detail
  - [x] Get referendum post data, onchain data, and timeline
  - [x] Edit post
  - [x] Post and edit comments
- [ ] Gov2 referenda subscriptions

**Comment by wliyongfeng** [comment]
Gov2 referenda will be solved in another issue.
