### ISSUE TITLE
Implement fold and unfold feature to sidebar

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#2192]
- [x] gov1 #2212 
- [ ] gov2

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9484%3A44367&t=hHNiVjR4f2m1cHXP-4)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/200996945-83e97ca7-66a1-40e8-bcdf-8ecab038bf73.png">

**Comment by Popoulosss** [comment]
Modify the layout of siderbar
- Subtitle cell padding to '12px 0px'
- tab cell padding to '10px 18px'

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/201020056-51c69125-49be-4c6e-a143-c4e32f15d585.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/201020157-b0556cb2-1986-455c-ab22-674134c45ac8.png">

**Comment by 2nthony** [comment]
memoize last fold status

**Comment by wliyongfeng** [comment]
Gov2 support don't have to be a task in this issue. We won't implement it in a very short time.
