### ISSUE TITLE
Support for Proxy

### ISSUE THREAD

**Issue by chevdor** [opensquare-network/subsquare#2201]
Currently, proxies appear to be unsupported.

With the growing number of mobile and desktop wallets, users will have also a growing amount of account unless putting accounts at risk and reimporting everywhere. A secure option is to use proxies.

A user with an account A could create a new account B for say another wallet on mobile or dekstop and define B as "Gov Proxy" for A. In my specific case, A is a council member but it also extends to non council members and Gov v2.

In terms of UI, this has several consequences:
- Any proxy of A that allows gov/Council should be detected as such. So even if B is not a council member, since it is a gov proxy or A, it should be listed as council member
- When voting using B, if B is considered as council member, it should send a proxy call on behalf of A and not a direct call from B

**Comment by chevdor** [comment]
>  adding proxy interfaces to various modals 

Beware, that should not require any visible UI change I think.  

> show B as a councilor, especially on councilor dedicated pages like [council members](https://kusama.subsquare.io/council/members)

100% agree

> For example, we should enable some buttons which will only be enabled for councilors?

Exactly, connnecting as B, if B is proxy for A and A is councillor, then I should see the council functions.

**Comment by wliyongfeng** [comment]
> Beware, that should not require any visible UI change I think.

There maybe some unexpected logic branches here if without pre-settings. For example, should we wrap a `democracy#second` call with proxy for B? 

I think we can add a proxy setting section on the [settings](https://kusama.subsquare.io/setting/key-account) page, if B set a proxy, all the calls will be wrapped by proxy. Though subsquare will do proxy verification and regular invalidity checking, it will become much easier for subsquare to handle logics with this convention.

**Comment by wliyongfeng** [comment]
Hey @chevdor , I'm happy to invite you to try proxy feature on [kusama subsquare](https://kusama.subsquare.io/setting/proxy). If A is a proxy of B:
1. Login with A
2. Go to the proxy setting page, and input B.
3. All extrinsics will be wrapped in proxy#proxy call. 
4. A will have authorities of B.

We will deploy it for polkadot soon.

**Comment by chevdor** [comment]
I tested on gov2, initially I skipped your step 2. thinking I already did it.
I ended up doing step 2. to be sure, not knowing if subsquare stores the information locally or not.
After doing step 2. it looked better and I could now see the balance of B and send a proxied call.
So it looks very promising.

Using Gov2, I got a "Call filtered" error when voting. Does this work for you? (There are plenty of props that can be voted on).

**Comment by wliyongfeng** [comment]
> not knowing if subsquare stores the information locally or not.

It's stored to the backend database. No worries about settings loss. But if we change the proxy relationship maybe in polkadot apps, we have to unset this address manually on subsquare, or the proxy call will produce an error.

> Using Gov2, I got a "Call filtered" error when voting. Does this work for you? (There are plenty of props that can be voted on).

I tested on the [development environment](https://development.subsquare.io/referenda/referendum/70), and it works. [Here](https://gov2.statescan.io/extrinsic/1718049-1) is my extrinsic. I also tried voting gov2 referendum without a proxy and it works.  Could you provide a screenshot for the error 🙏 ? And sorry, I didn't get the point for 'plenty of props'.

**Comment by wliyongfeng** [comment]
I close this issue since no further info. Please open new ones if new problems.
