### ISSUE TITLE
Add cookie consent on home page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2215]
Problems:
- Can a user reject cookies?
- What we should do if a user reject cookies?
- Design a interface for user.

---
Updates:
- No `reject` button, `Got It` button instead.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10914%3A53446&t=1nURIoZaF5k4LU0N-4)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/203784882-79cb73ec-088b-40e4-b42a-aa20ced99502.png">

**Comment by wliyongfeng** [comment]
Etherscan example:

![hAA1mPIwq3](https://user-images.githubusercontent.com/2264908/204544252-aa23d148-df68-48ab-b899-55646e3637f5.jpg)
