### ISSUE TITLE
As a user, I want to see a count down component for deciding/confirming referendums

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2217]
Like motions, we can add count down components to gov2 referendum list ~and detail~ page.

**Comment by Popoulosss** [comment]
Notice: only add a countdown component to the list page.

**Comment by Popoulosss** [comment]
Refer to gov1

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9491%3A45325&viewport=-757%2C488%2C0.79&t=I9sU1Cx28pvpCcnv-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/201571228-f4d480d1-0188-4fb9-aee3-3beb0819cb31.png">
