### ISSUE TITLE
Add democracy and tech-comm motion subscriptions

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/subsquare#2219]
- [x] design the UI democracy and tech-comm subscriptions (@Popoulosss )
- [x] Implement

```javascript
  tcMotion: {
    proposed: "tc_motion_proposed",
    voted: "tc_motion_voted",
    approved: "tc_motion_approved",
    disApproved: "tc_motion_dis_approved",
    executed: "tc_motion_executed", // for kintsugi/interlay only
  },
  democracyPublicProposal: {
    proposed: "democracy_proposal_proposed",
    canceled: "democracy_proposal_canceled",
  },
  democracyReferendum: {
    started: "democracy_referendum_started",
    passed: "democracy_referendum_passed",
    notPassed: "democracy_referendum_not_passed",
    cancelled: "democracy_referendum_cancelled",
    executed: "democracy_referendum_executed",
    notExecuted: "democracy_referendum_not_executed", // can not be executed due to error: PreimageMissing/PreimageInvalid
    fastTrack: "democracy_referendum_fast_track", // for kintsugi/interlay only, they will fast track referendum
  },

```

**Comment by Popoulosss** [comment]
Tech. Comm motions(proposals)
- Pay attention to kintsugi/interlay

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10219%3A50282&t=XT5clW33n8NqsTOU-4)

**Comment by Popoulosss** [comment]
Tech. Comm motions(proposals)
- For motons which dont have index, show abbr of hash

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/201854566-068083c7-3fa2-43c4-acd5-d86a4132891e.png">

**Comment by Popoulosss** [comment]
Democracy public proposal & external proposal & referendum
- Please check the comments on Figma
- Pay attention to [fast track of kintsugi/interlay](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10342%3A52458&t=I8lrirc2LCISxww0-4)

Figma link
[Email template](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10337%3A52364&viewport=-8711%2C6092%2C0.51&t=I8lrirc2LCISxww0-11)
[Subscription settings](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10342%3A52470&t=I8lrirc2LCISxww0-4)

**Comment by Popoulosss** [comment]
For motions and tips which dont have index, show abbr of hash

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/201857169-44194a79-a388-472a-ab31-975e062e69bd.png">
