### ISSUE TITLE
Implement breadcrumb to replace back button

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#2248]
For gov2

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9609%3A45398&t=h4idu0DQ4HbP3tb1-4)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/201939151-7a6abf9d-1583-4672-81ac-d11d081ef541.png">

**Comment by Popoulosss** [comment]
For gov1 (to be added)

**Comment by 2nthony** [comment]
### current stage

<img width="265" alt="image" src="https://user-images.githubusercontent.com/19513289/202348508-b6390aa6-46a2-4196-bcd4-7125abe0c982.png">
