### ISSUE TITLE
Support users to set proxy address

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#2251]
- [x] Proxy setting page
- [x] Only key account can set a proxy

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10454%3A52180&viewport=-80%2C-3423%2C0.43&t=gAn97MOElh9JULsi-11) (updated)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/205245715-988b1151-cce1-4c47-bb97-bf564d993998.png">

**Comment by Popoulosss** [comment]
- [ ] Display proxy state

Figma link

Preview

**Comment by wliyongfeng** [comment]
Note:
1. Only key account can set a proxy
2. For account with a proxy set, all extrinsics will be wrapped by `proxy#proxy` calls. Refer [here](https://wiki.polkadot.network/docs/learn-proxies#proxy-calls) for proxy calls.
3. We should show the proxy account on every sign modal for key account who have set a proxy.
