### ISSUE TITLE
As a user, I want to set delegation for a specific track on gov2

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2262]
For a specific track, I want to:
1. Delegate my vote to a user.
2. Remove my delegation when I want.
3. View my delegation.

**Comment by Popoulosss** [comment]
- [ ] Modify layout of [track description panel](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10541%3A50604&t=hAqj9K9F8WRK04C6-4)
- [ ] [Implement delegate popup setting window](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10534%3A51570&t=hAqj9K9F8WRK04C6-4)

Preview
