### ISSUE TITLE
As a user, I want to see my votes on the referendum detail page, so I can decide whether I have to vote again

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2263]
Show me following informations:
- Vote balance
- Conviction
- Whether through delegation

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9688%3A47382&viewport=-9129%2C669%2C0.87&t=mDUVFsqM0vb9lss2-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/202638183-7e6af1eb-e976-4261-88fa-b3edba34f2cf.png">

**Comment by wliyongfeng** [comment]
We also need it for democracy pallet.
