### ISSUE TITLE
As a user, I want to see amount statistics for various governance sections, so I can quick jump to the section with ongoing proposals

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2266]
- Treasury: how may proposals/bounties/child bounties/tips are going
- Democracy: how many public/external proposals and how many referendum are going
- Council/TC motions statistics

**Comment by Popoulosss** [comment]
[Figma link (to be polished)](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10663%3A57454&t=gvX1Qk8tvzrwJQil-4)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/203486658-d689ad6e-be58-4907-9ecf-4ce9283aa414.png">

**Comment by 2nthony** [comment]
The overview link should be use the `a[href]`
