### ISSUE TITLE
Deploy an instance for rococo testnet

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2287]
For test purpose.

**Comment by Popoulosss** [comment]
Files
[project-rococo.zip](https://github.com/opensquare-network/subsquare/files/10040169/project-rococo.zip)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/202672548-f5bbf947-aaee-4500-823f-043d67cfc62e.png">

**Comment by wliyongfeng** [comment]
https://rococo.subsquare.io/
