### ISSUE TITLE
breadcrumb long text in mobile

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#2291]
temporary fixed in #2293 , hide the second item

<img width="418" alt="image" src="https://user-images.githubusercontent.com/19513289/202645553-0c152a73-72da-4dcb-8250-37faef7faaa6.png">

**Comment by Popoulosss** [comment]
- [ ] Remove the last 'Referendum'

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/202671673-2eb78e53-43af-40d9-a5de-05d6af00f0eb.png">
