### ISSUE TITLE
Design todos

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2304]
- [x] Statistics on overview page: #2266 
- [x] #2341
- [x] Cookie consent: #2215 
- [x] #2359 
- [x] #2363

**Comment by Popoulosss** [comment]
- [ ] #2307

**Comment by Popoulosss** [comment]
- [ ] #2308

**Comment by Popoulosss** [comment]
- [ ] #2322

**Comment by Popoulosss** [comment]
- [ ] #2324

**Comment by Popoulosss** [comment]
- [ ] #2340

**Comment by Popoulosss** [comment]
- [ ] #2347

**Comment by Popoulosss** [comment]
- [ ] Move the position of proposals tag
