### ISSUE TITLE
If the user is not logged in but try to use product, popup connect wallet window 

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#2308]
- [x] Only the extentsion wallet can be connected, and the username/email login entry is not displayed

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10620%3A54634&t=tikmIKiiltOCwgfs-4)

**Comment by wliyongfeng** [comment]
Related issue: #2250
