### ISSUE TITLE
Leave more space for child bounty value

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2334]
![Vi67RvyvIc](https://user-images.githubusercontent.com/2264908/203321215-489b78b8-f04c-49ad-9980-675865358ae2.jpg)

**Comment by Popoulosss** [comment]
Fixed by @2nthony 

<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/203459203-18bdc692-60de-4041-ac8f-f4eec27b0813.png">
