### ISSUE TITLE
Implement 'Been delegated' feature and support checking all delegated data

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#2340]
- [x] Add a divider line to separate content and data
- [x] Change 'Delegate' to 'My Delegate', implement button hover effect
- [ ] 'My delegation' info bar
- [x] Modifiy 'Remove' button to icon button, implement button hover effect, display tooltip when hovering on it

[Figmal ink](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10106%3A49016&viewport=-1478%2C451%2C0.58&t=gvX1Qk8tvzrwJQil-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/203488553-460064d6-1ce8-4ba8-a547-dcaa37d66b23.png">

---

- [ ] 'Been delegation' info bar
- [ ] Add a 'Detail' icon button, implement button hover effect, display tooltip when hovering on it

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10106%3A49016&viewport=-2071%2C291%2C0.8&t=gvX1Qk8tvzrwJQil-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/203488624-e3b62846-2a98-4704-b257-8a53cfd0db90.png">

---

- [ ] Display all addresses that had delegated to current account (address), including address/identity, conviction and support
- [ ] Add tab to display 'Direct' addresses and 'Nested' addresses

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/204484631-d370aba5-5cbf-44dc-9758-91079d5e1f67.png">

**Comment by Popoulosss** [comment]
- [ ] Change the space value between the data cell from 0px tp 16px

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/203482920-1c814c95-e91d-48ea-9fdd-ffd2179f8b87.png">

**Comment by wliyongfeng** [comment]
ConvictionVoting query delegated sample code:

https://github.com/opensquare-network/play-dot/blob/main/src/gov2/convictionVoting/storage/votingFor/delegated.js
