### ISSUE TITLE
As a user, I want to see all the confirmation periods in one bar

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2359]
There may be several confirmation periods happen in one referendum decision period. We should put all these confirmation periods in one bar. If there are n confirmation periods:
- It's sure that 1...n-1 period are failed.
- N th period maybe confirming, succeed or failed.

**Comment by Popoulosss** [comment]
- [ ] Change 'Decision period' to 'Decision'
- [ ] Change 'Confirming period' to 'Confirmation'
- [ ] Display detail ('Started from XX, last for XX') when hovering on the failed periods

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9688%3A47382&viewport=-4217%2C-2880%2C0.87&t=AD55V2JW0xDJ41tz-11)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/203888761-1e2dd093-c118-4e89-b519-6669e525db4f.png">

**Comment by Popoulosss** [comment]
- [ ] Fix the color of confirmation bar color

[Link](https://kusama.subsquare.io/referenda/referendum/0)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/203888980-02d0e5b1-0ec6-4caa-a03e-b275cf84ba69.png">

**Comment by Popoulosss** [comment]
- [ ] Fix font weight

[Link](https://kusama.subsquare.io/referenda/referendum/0)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/203889199-1c2cd6a3-99f0-4aeb-a62c-31695adbff38.png">
