### ISSUE TITLE
gov2 Show ayes/nays bar on top of the gov2 referendum tally 

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2363]
![Nr2zsN3sy9](https://user-images.githubusercontent.com/2264908/203903760-d2079b8e-34e2-42b4-bdf7-81e0706852b6.jpg)

Similar with above that, but no passing mark, no threshold text.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=9609%3A45398&viewport=293%2C-2873%2C0.83&t=AD55V2JW0xDJ41tz-11)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/203913622-cfdcd447-63e7-475b-aae3-fc1395cb3bff.png">

**Comment by 2nthony** [comment]
both referendum: gov1/gov2
