### ISSUE TITLE
As a user, I want to see the comments count of subsquare and polkassembly on proposal detail

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2389]
![oeUeDGoGoR](https://user-images.githubusercontent.com/2264908/204565796-0238a9e3-cde3-429a-aff6-83658a6918cb.jpg)

**Comment by Popoulosss** [comment]
- [ ] Modify the width of tab box
- [ ] Display comments count

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=7212%3A49028&viewport=-787%2C-8320%2C0.87&t=oPRRQvQom2hsGnbU-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/204773448-494ff7f3-58df-434a-9885-3669ff98c940.png">
