### ISSUE TITLE
gov1 Optimize panel layout for overview

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#2396]
based #2386 

- [x] may extract this as a component from existed(referenda summary)
- [x] feat: summary, remove items, and support `children`
- [x] may need an api to fetch the counts @hyifeng 
- [x] main repo
- [x] kintsugi
   - [x] hide non-exists items
- [x] tow items per line in mobile
- [ ] test

Overview

<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/204490145-a7aae762-ea35-4b21-a099-5451953de742.png">

<img width="590" alt="image" src="https://user-images.githubusercontent.com/19513289/205234167-99d45440-e902-42db-a200-a3773f602d19.png">

**Comment by wliyongfeng** [comment]
1. Cursor becomes hand when hover the number, and the number should be a link to the corresponding router.
2. Not show items with 0 active proposals
