### ISSUE TITLE
As a user, I want to subscribe gov2 referendum events, so I can get notifications 

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2397]
Events:
- Submitted
- DecisionStarted
- ConfirmStarted| ConfirmAborted|Confirmed
- Rejected|Approved|TimedOut
- Executed

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11247%3A86344&viewport=1314%2C1475%2C0.5&t=jU2OZnPqyPhCY6Us-11)

**Comment by Popoulosss** [comment]
Optimize the email title(?)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/205417914-e0d52e29-cd16-4a7a-a780-e66c315044aa.png">
