### ISSUE TITLE
As a user, I want to see gov2 referenda curve charts, so I can know the referendum thresholds

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2399]
- Mini chart on track panel
- A modal is shown when we click the icon on mini chart. The chart will have more details on modal:
  - x/y axis
  - Picked data calculated threshold
  - More detailed data when mouse hover on the chart
- The user should be able to open the curve chart on referendum detail page. Current threshold should be shown as dots on it.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11068%3A52716&viewport=-2107%2C443%2C0.35&t=yuhadsOv8fPWW9AX-11)

Preview
Mini chart
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/205055424-4962d586-b86c-4a69-a991-78a2f6c1e703.png">
Detail chart
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/205055576-a6d6739b-ca4f-43de-8578-2e7611ac0985.png">

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11220%3A53620&viewport=-5111%2C-1941%2C0.61&t=gAn97MOElh9JULsi-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/205218117-ebd0d395-b86f-4237-bbea-5fd8db8c82b3.png">
