### ISSUE TITLE
As a user, I want the `cmd+k` shortcuts to navigate routes, so I can go to the target location with less time

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2422]
Currently there are too many categories of governance proposals, and we have to switch between gov1 and gov2. A `cmd + k` shortcut and search feature will help a lot to locate the target category.

**Comment by 2nthony** [comment]
https://github.com/pacocoursey/cmdk

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11578%3A60350&viewport=884%2C-803%2C0.34&t=7SP1gzVxrplAl6Op-11)
