### ISSUE TITLE
As a kintsugi/interlay user, I want to see my vKINT/vINTR balance on the democracy panel

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2439]

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11648%3A58590&t=G4awCLNfJJTSp7fM-4)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/207012594-3eff56fa-dae0-4757-a5a4-fb7138ba1525.png">
