### ISSUE TITLE
Show the minimum Dan level for a Fellowship referendum

### ISSUE THREAD

**Issue by Tbaut** [opensquare-network/subsquare#2442]
Hello there. As a fellow, I would like to know if a referendum is limited to some specific Dan level on Subsquare.
E.g this one https://kusama.subsquare.io/fellowship/referendum/12 is limited to Dan3 and above, and there are currently no way to see this on Subsqure.

On pjs/apps it's here for instance
![image](https://user-images.githubusercontent.com/33178835/206903173-4899e8d8-a950-4338-8ecf-f8a6fc426aae.png)

**Comment by wliyongfeng** [comment]
Hi @Tbaut , thanks for reaching out. I think we can see this info on the [track page](https://kusama.subsquare.io/fellowship/track/3), and we can also reach this page by clicking the breadcrumb fellows item on top of the referendum detail page.
![ZjEGhurDXI](https://user-images.githubusercontent.com/2264908/206904860-ab69746f-c581-4fd7-828d-8d5b0d1f14fd.jpg)

**Comment by Tbaut** [comment]
Got it thanks, the fact that it has a `#` in the front, just like the proposal numbers, and so many more numbers on the pages made me think this was not related. Feel free to close :)

**Comment by wliyongfeng** [comment]
Thanks for reaching out again. If `#3` is an important item for your business, I think your request makes sense. I'll discuss this with my designer.

**Comment by Tbaut** [comment]
All the fellowship members would certainly benefit from it. The reason is, I want to know whether this is a referendum I can sign or not. If it's limited to Rank X and higher, it's important for us to know.

**Comment by Popoulosss** [comment]
TBD
- To distinguish from the referendum number `#n`, use `[n]` as the number of track
   - Modify the format of number from `#n` to `[n]` in track info panel
- Show the track number `[n]` of the fellowship in the breadcrumbs

Preview
Track info panel
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/227091400-e6957e64-8e38-4f2d-9c53-5a4d5684f797.png">
Breadcrumb
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/227091616-c5bc757a-dd9d-4aa1-991b-aaf9bcec0c9b.png">

**Comment by wliyongfeng** [comment]
@Tbaut It's released. Let me know if it's still not enough.

**Comment by Tbaut** [comment]
Awesome, took me some time to come to it. It's very helpful <3
