### ISSUE TITLE
Support nested comments

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2463]
As users and posts grow, there are posts with many comments. Nested comments feature will help users focus on sub-topic raised by a comment.

**Comment by Popoulosss** [comment]
- [ ] Support to reply comment, display the input box below the comment
- [ ] Support to reply secondary comment, display the input box below it
- [ ] Secondary comments fold by default

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11752%3A56400&t=5W6LN634xIsQlASb-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/207815688-df0f7fc8-b977-4397-b369-ee618d5e1cad.png">
