### ISSUE TITLE
Show fellowship referenda votes

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2477]
- [x] Read votes from storage
- [x] Show votes on page

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10149%3A50209&t=YT8aL3d8GFp4Wbsz-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/208340368-3d2a6ed3-4221-4abc-855b-60bcd56e8d86.png">
