### ISSUE TITLE
Voting method enhancement

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#2542]
Refer to [vote on referendum](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.onfinality.io%2Fpublic-ws#/referenda)

[For Democracy, 3 options](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10405%3A49957&t=z6mHqkFKcD5sKtj2-11)
- Aye
- Nay
- Split

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/215256357-373a9c04-b9a3-4d84-b04c-d0fdba4292d0.png">

---

[For OpenGov, 4 options](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=10405%3A49957&t=z6mHqkFKcD5sKtj2-11)
- Aye
- Nay
- Split
- Abstain

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/215256391-2669da29-6848-4029-afa8-286b18324754.png">

**Comment by wliyongfeng** [comment]
Note that kintsugi/interlay don't have split/abstain vote type.
