### ISSUE TITLE
Implement the feature of post labels in discussion

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#2608]
- There are default labels depending on the project, suck as 'Proposal', 'Feedback', 'Request', etc. (TBD)
- Maximum: 2 labels

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=12603%3A62308&t=qViLOwYYiOBRhvbj-11) (updated)

Preview
Select label
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/217168744-a5d0dfcc-6a05-4cab-84b5-fbdca48aa516.png">
Display in card(tag is unclickable)
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/217168265-ddf406cf-edd0-4c36-8d40-f18ae9224d3e.png">

**Comment by Popoulosss** [comment]
- [ ] Fix the font size

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=7121%3A50573&t=vGuEIgwb7Zy70C9d-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/217169498-5742cfae-5795-4494-8610-77454129dbcc.png">

**Comment by Popoulosss** [comment]
- [ ] Modify the margin top and bottom to 24px

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=7121%3A50573&t=vGuEIgwb7Zy70C9d-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/217169820-cde8ad09-2410-4966-83d0-22aa060ec4c3.png">

**Comment by wliyongfeng** [comment]
Related: #1488
