### ISSUE TITLE
  Unable to report an on-chain Treasury proposal post on Subsquare

### ISSUE THREAD

**Issue by anaelleparity** [opensquare-network/subsquare#2660]
Hello there,

We have a scammer trying to use the on-chain treasury and Subsquare as a platform for phishing schemes here: https://polkadot.subsquare.io/treasury/proposal/238

Would it be possible to add a **report button** to flag dodgy on-chain treasury proposals to your moderation team? 
Further developments could include a notification service connected to Kusama/Polkadot forums (Element, Discord, etc.)

Please advise.
Thanks!

**Comment by wliyongfeng** [comment]
Hi, thanks for letting me know. Do you have any ideas about how to handle scammer posts? Show special warnings if confirmed by moderation team?

**Comment by anaelleparity** [comment]
For now, what I have done is to flag the proposal as phishy in a comment so that the community does not fall for it.

Scammer posts that are submitted as an on-chain proposal (with a deposit paid and all) are hard to take down straightaway, because they will require on-chain governance to cancel them. 
However, I think we should be able to report them and subsequently add a warning icon on the interface while they are being investigated. If confirmed as actual phishing schemes (like in today's case), we could then add a no-entry icon on the interface.

I will discuss this with the governance team: we might be able to come up with a formal procedure and share it with all the platforms supporting governance operations.

Thanks! :pray:

**Comment by Popoulosss** [comment]
- [ ] Implement warning notice.

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=6658%3A962721&t=DLdXLOKlBahY5c0f-11)

Preview
<img width="695" alt="image" src="https://user-images.githubusercontent.com/59445675/222389375-89d70722-f4dc-4e9a-a7f4-61bfb4688240.png">

**Comment by anaelleparity** [comment]
Thanks for sharing these upcoming additions, @Popoulosss!
I would suggest something along the following lines for the wording: **"Warning: Malicious proposal! Some of the external links below have been flagged as scams."**

Cheers! :)

**Comment by Popoulosss** [comment]
> Thanks for sharing these upcoming additions, @Popoulosss! I would suggest something along the following lines for the wording: **"Warning: Malicious proposal! Some of the external links below have been flagged as scams."**
> 
> Cheers! :)

Updated. Much appreciated :D

**Comment by wliyongfeng** [comment]
Released. https://polkadot.subsquare.io/treasury/proposal/238
