### ISSUE TITLE
feat: page calendar

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#2661]
figma: https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11413%3A60913&t=iW2j8AJFSRJXNDcV-0

- [x] #2675
- [x] #2672
- [x] #2673
- [x] #2674
- [x] #2694

**Comment by 2nthony** [comment]
http://react-component.github.io/calendar/
https://fullcalendar.io/docs/react

**Comment by Popoulosss** [comment]
> figma: https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11413%3A60913&t=iW2j8AJFSRJXNDcV-0

Updated

---

- Calender panel
- Events panel
- Create event process

Figma link

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/221539338-b2b8b9f1-d5ab-49f0-8c5f-61c30a7a8472.png">
