### ISSUE TITLE
calendar, create event

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#2674]

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=12922-64169&t=lnXCbSC3lxrOWvjf-0)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/227862541-6480aa5c-8d2b-4751-bed3-2b72ca13f25d.png">

**Comment by Popoulosss** [comment]
- Hide the 'Today' button and use icon button represent 'Create Event' in mobile layout

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/227863115-794b687a-a171-41fe-8094-25196caaf998.png">

**Comment by Popoulosss** [comment]
- Add ‘End date’ when create a new event

Figma link
- [Setting end date](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=11439-61870&t=zZhOy3DXP2KYjjsv-11)
- Show the ‘started’ and ‘ended’ event card in calendar list

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/230264617-d6558cca-7e7b-4522-994a-52ed9c84a7b9.png">
