### ISSUE TITLE
Show democracy turnout percentage

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2721]
We should show percentage value of democracy referendum turnout.

Current solution:
![image](https://user-images.githubusercontent.com/2264908/223423513-41fe20c6-fb06-4cf9-a8f5-53176502acca.png)

In polkadot apps:
![Apn9e2AzXQ](https://user-images.githubusercontent.com/2264908/223423636-f8082bd6-109d-4b77-b39d-32346a74e2e0.jpg)

**Comment by Popoulosss** [comment]
- [ ] Percentage are shown as suffix in turnout, as well as vote numbers for aye and nay

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=7375%3A63981&t=NjffjOyEiJSUe2AN-11)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/223468469-eddb87d1-f4aa-4926-bc6e-6f552b47312f.png">

**Comment by wliyongfeng** [comment]
@2nthony Note: show the percentage value only when `electorate` is loaded.
