### ISSUE TITLE
When the second has reached the max deposits, hide the 'Second' button and show the prompt

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#2811]
- [ ] Show the current 'Second' number and the max number
- [ ] Modify the font size and font color
- [ ] When the 'second' has reached the max deposits number, hide the 'Second' button and show prompt

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=13683-74346&t=zZhOy3DXP2KYjjsv-11)

preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/230336705-4c775b0a-b170-4d6a-a0ed-bac1bbf93561.png">

**Comment by wliyongfeng** [comment]
#2810
