### ISSUE TITLE
incorrect support amount in percent

### ISSUE THREAD

**Issue by Nick-1979** [opensquare-network/subsquare#2832]
![Screenshot (48)](https://user-images.githubusercontent.com/46442452/233936866-4d4ef548-e828-447d-a311-41c9660e1260.jpg)

**Comment by wliyongfeng** [comment]
@Nick-1979 Thank you for the issue. Sorry I didn't get problem. Could you give more description?

**Comment by wliyongfeng** [comment]
> **0.18% or 1.8%**
> 
> The support on the chart is **0.18%** at that time, which is correct but in other places we see Support Threshold as **1.8%**, Which is not correct right? the same for Current Support.

1.8‰ === 0.18%. 
Please note that in other places it's 1.8‰ which is equal to 1.8%. We want to avoid preceding 0 in some places, so we use ‰ instead of %.
