### ISSUE TITLE
Support polkagate extension

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2837]
- website: https://www.polkagate.xyz/
- github: https://github.com/PolkaGate/polkagate-extension
- chrome extension: https://chrome.google.com/webstore/detail/polkagate-the-gateway-to/ginchbkmljhldofnbjabmeophlhdldgp?hl=en-US

**Comment by Popoulosss** [comment]
Res
[icons-logo-wallet-polkagate.svg.zip](https://github.com/opensquare-network/subsquare/files/11319838/icons-logo-wallet-polkagate.svg.zip)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/234204331-bf03ec72-9a8b-453c-bf1b-ffbadd885a13.png">

**Comment by AMIRKHANEF** [comment]
Hello OpenSquare Team,

I am Amir from PolkaGate team, I wanted to inform you that I have submitted a pull request to the SubConnect repository. You can find the pull request [here](https://github.com/Koniverse/SubConnect/pull/29).

I would appreciate it if you could take a look and provide your feedback.

Thank you for your attention.

**Comment by wliyongfeng** [comment]
@AMIRKHANEF PR is merged. It will be released soon.

**Comment by AMIRKHANEF** [comment]
> @AMIRKHANEF PR is merged. It will be released soon.

Wow, that's fantastic news! Thank you so much for informing me. I'm extremely grateful!
