### ISSUE TITLE
Darwinia network integration

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2852]
Related media resources can be found [here](https://itering.notion.site/About-Darwinia-Network-033b9802511c4c88854477a064391a9c).

**Comment by Popoulosss** [comment]
Files
[project-darwinia.zip](https://github.com/opensquare-network/subsquare/files/11399212/project-darwinia.zip)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/236254234-f38beed3-6c3c-47f7-86c1-a3589e5026f4.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/236254451-2830249b-f737-46d5-a0e1-6e5389270d59.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/236258551-83db6433-999b-4066-9b31-4e3f08fcc77b.png">
