### ISSUE TITLE
As a user, I want to filter OpenGov referenda by status

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2908]
Possible values:
- Preparing
- Queueing
- Deciding
- Confirming
- Cancelled
- Killed
- TimedOut
- Rejected
- Executed

**Comment by Popoulosss** [comment]
- Implement a filter bar
  - Show the title and current amount of referenda
  - Add the status select, `All Status` is showed by default
     - Provide filter values
     - If necessary, show the a representative color for each status

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?type=design&node-id=15207-75868&t=4VnFeMW2QB7bi7qm-11)

preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/97d72aa3-2b54-4eab-803c-5d3ab27c7f91">

**Comment by Popoulosss** [comment]
**Additional**

- [ ] If we show the total amount of referenda in filter bar, [we can remove this number from info card](https://kusama.subsquare.io/referenda/track/0)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/1e6c7d00-bb3d-4305-b7b8-5f73bbafcdbb">

---

- [ ] Fix the font size to 14px, refer to `New Post`

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/8be8f68f-c5b4-4613-870c-3d8fce7f6f22">

**Comment by Popoulosss** [comment]
- [ ] Modify the index from `#n` to `[n]`

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/35d297e0-52e6-4179-93dc-57337f82dd71">
