### ISSUE TITLE
ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2964]
How to reproduce, test interlay: http://127.0.0.1:7002/democracy/referendum/53

![myhBWgGVaL](https://github.com/opensquare-network/subsquare/assets/2264908/6d93df04-ffd2-48a7-9353-655c077ded95)

**Comment by 2nthony** [comment]
https://github.com/opensquare-network/previewer/issues/58

**Comment by 2nthony** [comment]
https://github.com/opensquare-network/previewer/issues/60
