### ISSUE TITLE
Add a link to dotreasury on subsquare treasury panel

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#2976]
Text: Statistics, link to: https://www.dotreasury.com/ksm or https://www.dotreasury.com/dot

**Comment by Popoulosss** [comment]
- [ ] Show the statistics entrence in treasury pages(proposals, bounties, child bounties and tips)
- [ ] Only implement on Polkadot and Kusmsa space, `Statistics` link to: https://www.dotreasury.com/ksm or https://www.dotreasury.com/dot
- [ ] Abbreviate `New XX` to `New`, `Statistics` to `Stats` in the text on the mobile layout
   - [ ] If necessary, implement this update to other mobile pages

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?type=design&node-id=15425-80465&t=xUVguaLXhdJ22dCv-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/b826b85c-98e1-46f6-9951-5f2ba151d2dd">

**Comment by Popoulosss** [comment]
- [ ] Modify the info panel of treasury pages(proposals, bounties, child bounties and tips)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a22d258f-8123-474b-935b-4bd9f254a168">
