### ISSUE TITLE
!v2 nav(menu)

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#2983]
notice, has customized color, e.g. theme100, theme500

- [x] icons
- [x] when is collapsed, float submenu if has
- [x] read cookie collapsed
- [x] follow active

**Comment by Popoulosss** [comment]
Customized color res
[color.js.zip](https://github.com/opensquare-network/subsquare/files/11704499/color.js.zip)

**Comment by Popoulosss** [comment]
Notice: The project logo hast wo versions: light and dark , they apply to different backgrounds.

Project logo res
[project logo.zip](https://github.com/opensquare-network/subsquare/files/11704506/project.logo.zip)

**Comment by Popoulosss** [comment]
- [ ] Add Bifrost Polkadot res

Files
[bifrost polkadot.js.zip](https://github.com/opensquare-network/subsquare/files/11712155/bifrost.polkadot.js.zip)
[project logo-bifrost polkadot.zip](https://github.com/opensquare-network/subsquare/files/11712156/project.logo-bifrost.polkadot.zip)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/2a99e154-508d-4010-a3c3-360a6a25a08c">
