### ISSUE TITLE
v2, chain description, social links

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#2991]
<img width="920" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/ddca8628-e456-4d08-8ccc-5c60d49a20b9">

**Comment by Popoulosss** [comment]
Website
`<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M7.52406 13.5996H12.4764C11.9805 16.2182 10.988 18 10.0002 18C9.04288 18 8.08072 16.3246 7.57045 13.8364L7.52406 13.6012V13.5996ZM2.85482 13.6004H6.29876C6.58989 15.2661 7.08497 16.6839 7.73201 17.6752C5.69854 17.0715 3.9869 15.6866 2.97159 13.8236L2.85482 13.6004ZM13.7025 13.6004H17.1457C16.6532 14.576 15.9666 15.4407 15.128 16.1414C14.2895 16.8421 13.3167 17.364 12.2693 17.6752C12.8731 16.7487 13.3442 15.4525 13.6409 13.93L13.7025 13.6004ZM13.9441 8.39984H17.8391C18.1091 9.72929 18.0384 11.1055 17.6335 12.4002H13.8713C13.9938 11.246 14.0285 10.0842 13.9753 8.92469L13.9433 8.39904L13.9441 8.39984ZM2.16219 8.39904H6.05722C5.97355 9.5767 5.98238 10.7591 6.08362 11.9354L6.12921 12.3994H2.36694C1.96181 11.1048 1.89082 9.72856 2.16059 8.39904H2.16219ZM7.26252 8.39904H12.7404C12.8317 9.57783 12.8218 10.7623 12.7108 11.9394L12.6612 12.3994H7.3401C7.20031 11.2015 7.16499 9.99359 7.23453 8.78948L7.26252 8.39904H12.7404H7.26092H7.26252ZM12.3557 2.45925L12.2693 2.32323C13.458 2.67638 14.5487 3.30047 15.4556 4.14646C16.3625 4.99246 17.0609 6.03731 17.496 7.19892H13.8249C13.5722 5.26593 13.0595 3.60496 12.3549 2.46005L12.3557 2.45925ZM7.63523 2.35284L7.73281 2.32323C7.02738 3.40414 6.50351 4.9875 6.22518 6.84689L6.17559 7.19892H2.50611C2.93519 6.05347 3.62041 5.02132 4.50939 4.1814C5.39837 3.34148 6.46756 2.71602 7.63523 2.35284ZM10.0002 2C11.0552 2 12.1165 4.0338 12.5708 6.9469L12.6084 7.19892H7.39209C7.82478 4.15142 8.91571 2 10.0002 2Z" fill="#9DA9BB"/>
</svg>
`
