### ISSUE TITLE
v2, list review

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3030]
see comments below, if done, then hide comment

**Comment by 2nthony** [comment]
<img width="1135" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/df959391-3504-4f88-9fd5-e3a6ce7aa314">

remove the member list width limitation

**Comment by 2nthony** [comment]
in large viewport

<img width="591" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/f0e89052-4a10-4d80-a3a2-0aa2d2e38607">

**Comment by Popoulosss** [comment]
- [ ] Off-chain -> Off-chain Voting
- [ ] Proposals -> Public Proposals
- [ ] External -> External Proposals
- [ ] Tech. comm. -> Technical Committee

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/ad1c50f6-9828-4c79-8df8-dbdf03ac5819">

**Comment by 2nthony** [comment]
collective

<img width="855" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/da177bef-0ad9-4f52-93c0-fc8110694db1">

**Comment by 2nthony** [comment]
referenda track, tweak summary items gap in large viewport

<img width="818" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/32f5edd6-871d-4308-827c-7bf36fa9fafc">

**Comment by 2nthony** [comment]
did not active the menu in statistics page

<img width="646" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/1396eddf-9e8f-4a7d-baee-88186c2b141a">

**Comment by 2nthony** [comment]
some title gap

<img width="331" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/2689f61a-bf25-4b45-ae71-3a7d1125ec58">

**Comment by Popoulosss** [comment]
feat: add open tech. comm. icon

- [ ] Reuse `menuFinancialCouncil` to treasury council
- [ ] Replace `menuOpenTechComm` icon

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/4ce7f238-c565-4ee2-ba8a-b88dda7814b0">

**Comment by Popoulosss** [comment]
- [ ] Show the subtitle in float menu

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=1476-50756&mode=design&t=yC3yWcxlzt7Cufz8-11)

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/82d81446-8f44-4c43-8e9b-17c9debd745f">

**Comment by Popoulosss** [comment]
- [ ] Hide the scroll bar in side menu

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/28e6b776-7d67-47ce-910b-a3fd8613ab08">

**Comment by Popoulosss** [comment]
- [ ] Archived `Democracy`, `Council`, `Technical Committee`

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=2106-52601&mode=design&t=yC3yWcxlzt7Cufz8-11)

<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a1679c66-4e9d-401d-acfb-6c2b9a251401">

**Comment by 2nthony** [comment]
- [ ] cmdk palette icon color

**Comment by Popoulosss** [comment]
> * [x]  Show the subtitle in float menu
> 
> [Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=1476-50756&mode=design&t=yC3yWcxlzt7Cufz8-11)
> 
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/59445675/249971031-82d81446-8f44-4c43-8e9b-17c9debd745f.png">

- [ ] Fix the position of the floating secondary menu, align the icon and text horizontally

Figma link

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/c8285b0c-0f6d-416d-85ac-243d5a343abc">

**Comment by Popoulosss** [comment]
- [ ] Show the menu text if there is no floating secondary menu when hovering over the icon while the side menu is folded

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=2138-52477&mode=design&t=0npjY802aRi2wxMz-11)

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/ae0d11a8-59a4-4299-a34f-5ce9ca3124d2">

**Comment by Popoulosss** [comment]
- [ ] Replace new icons for cmdk

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/e3fcd583-485b-4040-b5d0-dc81416d732b">

**Comment by 2nthony** [comment]
kintsugi pages switch listlayout
- calendar
- discussions

**Comment by Popoulosss** [comment]
- [ ] Change list background color from gradient color to solid color
   - [ ] light `neutral200`
   - [ ] dark `#1E2130`

**Comment by Popoulosss** [comment]
## header

### [Search bar](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=1112-26910&mode=design&t=Wljcunu28jTivKZM-11)

- [ ] Fix border radius to 8px
- [ ] Fix interaction color
   - [ ] default: bg neutral200, border no color
   - [ ] hover: bg neutral200, border neutral500
   - [ ] active/selected: bg neutral100, border neutral500

<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a93a539c-d6aa-490f-9570-f013f118e3ab">


---

### [Login button](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=1112-26910&mode=design&t=Wljcunu28jTivKZM-11)

- [ ] Fix border radius to 8px
- [ ] Fix height to 40px (same as the search bar)
- [ ] Fix color to theme500

<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/e460bcd0-98a4-4063-a276-86c61c986728">

---

### [Select component](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=1296-77281&mode=design&t=Wljcunu28jTivKZM-11)

- Username
- Network
- Node

- [ ] Fix border radius to 8px
- [ ] Fix height to 40px (same as the search bar)
- [ ] Fix interaction color
   - [ ] default: bg neutral100, border neutral400
   - [ ] hover: bg neutral100, border neutral500
   - [ ] active/selected: bg neutral100, border neutral500, arrow up (if available)
- [ ] Fix dropdown menu ui
   - [ ] border radius to 8px
   - [ ] border color neutral300
   - [ ] new ui
      - [ ] username
         - [ ] replace icons
      - [ ] node menu
   - [ ] fix subtitle in network font style

<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/ef5fb566-7af0-453f-9c6b-8540b6b24c9b">

**Comment by Popoulosss** [comment]
- [ ] Change all tab components' margin value to 1.5rem

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/7d3a9594-eb45-48a5-8afc-eb9bf2787d69">

**Comment by 2nthony** [comment]
- [ ] cookies consent

**Comment by Popoulosss** [comment]
- [ ] Optimize list filter ([select components](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=2269-60977&mode=design&t=oy4pNj7YGhB3AudX-11))

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/14ac3b5f-0403-46fb-bab9-63dcedf4229d">

**Comment by Popoulosss** [comment]
## Footer

- [ ] Text color to `textPrimary` when hovering over the text

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/7e7af8b5-cce4-43c5-88e6-a8e3a14d7a70">
