### ISSUE TITLE
v2, list pages

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3069]
- [x] v2 colors palette
- [x] chain customized colors
- [x] avoid flash, system appearance https://github.com/opensquare-network/subsquare/pull/2980/commits/f5430da97d467bfcdeb57813a2e8c5acb6a1085d
- [x] css 3 global vars
- [x] fonts css
- [x] system appearance
- [x] fix seo
- [x] cmdk
- [x] #2995
- [x] add more responsive breakpoint, like pad(1080px)
- [x] layout
   - [x] v2 list layout(home)
   - [x] kintsugi home page
   - [x] list pages
	    - [x] page discussions
		- [x] page polkassembly
		- [x] page calendar
		- [x] #3025
		- [x] page fellowship *
		- [x] page democracy *
			- [x] referenda
			- [x] proposals
			- [x] external
		- [x] page treasury *
			- [x] proposals
			- [x] bounties
			- [x] child bounties
			- [x] tips
		- [x] page council
			- [x] motions
			- [x] members
		- [x] page techcomm
			- [x] proposals
			- [x] members
		- [x] page financial council
			- [x] motions
			- [x] members
		- [x] alliance
			- [x] announcement
			- [x] motions
			- [x] members
			- [x] unscrupulous
		- [x] kintsugi all above
- [x] #2983
- [x] #2982
- [x] #2981
- [x] #2991 
- [x] #3012
- [x] #3014 
- [x] v2 post list title link icon position
- [x] v2, move `iconv2` as `icon` in `consts/menu`
- [x] #3045

**Comment by Popoulosss** [comment]
- [ ] Replace the `call` with `request` number in treasury referenda card,s refer to treasury proposals

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/493382cf-d876-4985-beaa-95f0090c7c34">
