### ISSUE TITLE
v2, detail pages

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3070]
- [x] detail layout
   - [x] discussions/post
   - [x] referenda
      - [x] detail
   - [x] fellowship
      - [x] detail
   - [x] treasury
      - [x] proposal
      - [x] bounties
      - [x] child bounties
      - [x] tips
   - [x] democracy
      - [x] referenda
      - [x] public proposal
      - [x] external proposal
   - [x] council
      - [x] motion
   - [x] tc
      - [x] proposal
   - [x] ...
   - [x] kintusi pages
- [x] v2, detail, fix un-finalized 404
- [x] v2, detail responsive should adapt `nav` collapsed or not
- [x] v2, all detail pages, should fetch `tracks` `fellowshipTracks` for nav menu
- [x] #3092
- [x] #3135
- [x] v2, detail tabs for call, metadata, timeline
- [x] #3083

**Comment by Popoulosss** [comment]
[Re-edit title and content](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=2490-55212&mode=design&t=iFI6dAjdhlDkAdY8-11)

- [ ] Click the `Edit` to re-edit the title and content
   - [ ] Disabled the proposal title when editing status

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/0fbd2087-c1d8-4136-8a6a-45887fb2f47c">

**Comment by Popoulosss** [comment]
If there is a confirmation bar displayed in the status panel:

- [ ] Show the `Zoom In`/`Zoon Out` icon in the title bar
- [ ] Show the `Zoom In` mode by default (full width confirmation bar)
- [ ] User can switch the mode by clicking the icon `Zoom Out` (confirming time in entire deciding period)

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=2845-68757&mode=design&t=IzYZVBLZLqGtGuRM-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/8c5dc4ad-6a89-4641-aee0-8d62adb95210">

**Comment by Popoulosss** [comment]
- [ ] Shorten the spacing between the `section` and `method`, change the margin left value from 8px to 4px

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=3057-106870&mode=design&t=s24X03hWx4ccRO3c-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/3865c614-d035-4674-b23a-295625d7c381">

**Comment by Popoulosss** [comment]
- [ ] Show the child `section.method`

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=3057-106870&mode=design&t=s24X03hWx4ccRO3c-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/2fb93526-4058-491b-b1d4-996817ae1ed7">
