### ISSUE TITLE
v2, detail review

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3083]

**Comment by 2nthony** [comment]
Democracy detail 页面的问题：
- [ ] Aye，Nay Tab 的颜色不对，背景和选中的颜色可能反了
- [ ] 固定popup到屏幕顶部的距离,aye nay 的高度不一致时切换抖动
- [ ] votes loading icon（spinner） 应该在中间，现在处于最坐标
- [ ] Votes popup会自动弹到最上边
- [ ] Nested popup 第二层popup打开之后，点击周围应该只close上层的popup

**Comment by 2nthony** [comment]
timeline throws an error, only in dev mode

<img width="679" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/dba0524e-ecfb-4746-974b-dc75a3cd5a19">

**Comment by 2nthony** [comment]
- [ ] radius

<img width="947" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/506042f1-1de7-4e99-9459-c6448560ef00">

**Comment by Popoulosss** [comment]
- [ ] Refine ui of `Bussiness`, `Metadata`, `Timeline`
   - [ ] Remove panel border
   - [ ] Modify layout

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=2587-59856&mode=design&t=kNx8gkNSsYsmGPeg-11)

**Comment by 2nthony** [comment]
- [ ] back to discussions @Popoulosss 

<img width="427" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/6acef24c-1059-4090-813a-9151e318ac1b">

**Comment by 2nthony** [comment]
- [ ] post meta right tag?

<img width="987" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/a9826012-3a21-43f4-90a2-b9404ccf5e6d">

**Comment by 2nthony** [comment]
- [ ] post meta

not child

<img width="533" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/1939cb16-5da6-4890-ba53-0a7a350e9be4">

**Comment by 2nthony** [comment]
- [ ] post content gap, right bar gap

<img width="1003" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/e6ba9857-341d-419e-b866-17482dcc26e3">

**Comment by 2nthony** [comment]
- [ ] treasury childbounty

<img width="990" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/1e3adbfe-d282-40c6-9ff6-a02d11f99145">

**Comment by 2nthony** [comment]
- [ ] missed layout

<img width="967" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/f4590911-ca9e-4b2f-8c5f-7394b51e6872">

**Comment by Popoulosss** [comment]
- [ ] Set the background color of detail page to #1C1F2E (refer to list page)

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=3038-104108&mode=design&t=7P2aZntLZfhjbdqV-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/005b0e5d-d0e5-4aba-9e8b-f0b9c7e6ac6b">

**Comment by Popoulosss** [comment]
- [ ] Fix the font color

[Link](https://rococo.subsquare.io/council/motion/34)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/664df046-b3f2-4b6d-ae7b-626eafa4eef2">
