### ISSUE TITLE
Special account view

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3165]
We should handle special special accounts view. Code [here](https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/AccountName.tsx#L60-L73).

![HBHviT1A1Q](https://github.com/opensquare-network/subsquare/assets/2264908/528d5d6d-b667-4ba8-8532-a56ac5c5a010)

![mA4wEZqDJ0](https://github.com/opensquare-network/subsquare/assets/2264908/07e6edd1-e12c-4761-a2fd-f92818c57b85)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1783-76860&mode=design&t=R9I0Vso7RdiUlz24-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/1fba4c14-ac83-468b-8aba-b82fc134d893">
