### ISSUE TITLE
v2, UI reviews

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#3245]
# UI reviews

**Comment by Popoulosss** [comment]
- [ ] Fixed the background color of selected text in dark mode in the editor, refer to 

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/55966025-8549-4867-8bd1-744257985095">

Refer to
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/15fe083f-a5ec-432c-9ce4-db81777886b4">

**Comment by Popoulosss** [comment]
- [ ] Add gap between title and action of `vote history card` in mobile layout
- [ ] Add gap between title and action of `vote management card` in mobile layout

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/3f2240b6-b603-43e6-8903-d801b4d9f750">
To
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/d1062fb4-54f3-43f2-8337-12754fd42575">

**Comment by Popoulosss** [comment]
- [ ] Fix the color of countdown component in dark mode
   - [ ] `yellow100`, `yellow500`

[Link](https://polkadot.subsquare.io/referenda)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/54163ac8-ad21-45ca-80c9-afe78fc414b5">

**Comment by Popoulosss** [comment]
- [ ] Add border(color: `neutral300`) to zoom handle

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1908-76399&mode=design&t=HsWWn14fL6ewSw2G-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/aed5b68b-4b46-4f2b-9f9f-e8c06e666385">

**Comment by 2nthony** [comment]
- [ ] remove the subtitle
<img width="619" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/859857fe-80dc-41fe-a5ce-4a1495c0a633">

**Comment by Popoulosss** [comment]
- [ ] Show the countdown in treasury info panel

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1908-65308&mode=design&t=HsWWn14fL6ewSw2G-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/591788af-4e54-4716-8bdc-7b6e41bc9807">

**Comment by Popoulosss** [comment]
- [ ] Fix the title height

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/5202c527-d381-47db-a749-0ea6a1bea00d">
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/edce12d4-e67d-42d3-8bee-f3d6c8840be7">

**Comment by 2nthony** [comment]
- [ ] update chain icons
<img width="426" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/29899c9a-2328-434d-9b12-e2cfcb8e3d81">

**Comment by Popoulosss** [comment]
- [ ] Fix the font weight of `+ New proposal`

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=4401-33060&mode=design&t=BqnF5Qo8E6s8rS5F-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/70199381-58a9-404c-9d18-94a22e371883">

**Comment by Popoulosss** [comment]
- [ ] Modify the progress bar from round to square (Keep the beginning and end corners rounded)
- [ ] Check list
   - [ ] Status bar
   - [ ] Support bar

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1611-50443&mode=design&t=R9I0Vso7RdiUlz24-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/7b59c964-718e-4963-ad7c-461c72c11b3a">

**Comment by Popoulosss** [comment]
- [ ] Fix avatar and user name alignment

[Link](https://polkadot.subsquare.io/discussions)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/8be8d7b4-5d57-4011-9d6b-7f3b2a8a3de8">

**Comment by Popoulosss** [comment]
- [ ] Modify the position of toggle component
   - [ ] Timeline
   - [ ] Votes stats
   - [ ] Comment

[Timeline](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1646-55198&mode=design&t=KTPusSpdsaFiYCCH-11)
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/f1bd8fa7-263c-4e0a-858e-2f1100c7674d">

[Votes stats](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=4576-31547&mode=design&t=KTPusSpdsaFiYCCH-11)
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/78e8daa9-1e2b-4c2a-8ce4-f67b25a9e634">

[Comments](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1924-58055&mode=design&t=KTPusSpdsaFiYCCH-11)
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/b0462ba4-c88e-4bcd-b854-f06fdf0729df">

**Comment by Popoulosss** [comment]
- [ ] Modify the `Comments` font style

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1924-58055&mode=design&t=KTPusSpdsaFiYCCH-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/947f310d-3d07-47a1-8655-c856f71fb07d">

**Comment by Popoulosss** [comment]
- [ ] Fix the title text alignment in proposal card

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/7ba1002c-5dc4-46da-97f6-36bafa861549">
