### ISSUE TITLE
circle packing bubble chart

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3326]
- [x] https://www.react-graph-gallery.com/circular-packing (https://github.com/holtzy/react-graph-gallery
   - [x] hover tooltip (pseudo code)(https://www.react-graph-gallery.com/scatter-plot#tooltip
   - [x] hover dim effect (https://www.react-graph-gallery.com/scatter-plot#hover%20effect
   - [x] middle text(address)

<details>
<summary>other research</summary>

- https://airbnb.io/visx/pack
- https://ant-design-charts.antgroup.com/en/examples/more-plots/circle-packing/#label
- https://vega.github.io/vega/examples/packed-bubble-chart/
- https://www.highcharts.com/demo/highcharts/packed-bubble (required license)
- https://echarts.apache.org/examples/en/editor.html?c=circle-packing-with-d3

</details>

**Comment by wliyongfeng** [comment]
https://d3-graph-gallery.com/graph/circularpacking_template.html

OR: https://d3-graph-gallery.com/circularpacking.html

![ExAEEsNOLu](https://github.com/opensquare-network/subsquare/assets/2264908/4114ed8f-4815-4c43-8892-4b687e35ffe1)

**Comment by Popoulosss** [comment]
- [ ] Implement empty status

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=4576-31547&mode=design&t=9RMqu0lnwVzBu5OK-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/0edb221f-9119-49a7-bd91-57686ec990c0">

**Comment by Popoulosss** [comment]
- [ ] Implement loading status

https://github.com/opensquare-network/subsquare/assets/59445675/8ae3ad03-758d-4812-b9e2-02069ab98926

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=4576-31547&mode=design&t=OcDhcgboMmpGW5vn-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/3c8aa70e-3fac-4ee2-b610-3cf409dc90b1">
