### ISSUE TITLE
Render call remark field with markdown previewer

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3354]
https://moonriver.subsquare.io/referenda/0

![Ih9SIHCjRN](https://github.com/opensquare-network/subsquare/assets/2264908/993b106c-4319-49d8-91ea-fb9c0113aec7)

**Comment by Popoulosss** [comment]
Keep the markdown style consistent with the proposal text

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1646-55158&mode=design&t=OcDhcgboMmpGW5vn-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/f7384a88-1fc4-437e-9953-f81cb8a44a5f">
