### ISSUE TITLE
Improve account connect/login process

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3423]
There should be 3 states for account login process: 
- connected, it means web3 account connect its address, without login in with message sign.
- logined, it means either web3 or web2 account has logined with authentication passed.
- none, it means no account is connected or logined.

Issues we should solve:
- User don't have to sign raw data to login before signing a extrinsic.
- Connected users have to sign raw message to login before leaving comments or creating posts.
- If a web2 account with an address linked, we should report error when a user try to sign an extrinsic but we can not find the address from extensions.

-----------------------------------------

- [x] Implement select wallet popup
- [x] If user is not login or user wallet is not available, then display select wallet before action
- [x] Remember the last used wallet
- [x] Implement new component to display selected wallet and able to switch wallet

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5822-31570&mode=design&t=RZApIkcvhEsj31x4-11)

Preview
Select wallet & choose address
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a2d1114b-e25e-4114-bfc4-6be723cd5c69">
Action
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/5faaafcc-c90b-4343-b686-4bd0b0d1dea2">

**Comment by Popoulosss** [comment]
- [ ] Show wallet icons at the bottom right of user avatar

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5822-32363&mode=design&t=2uAICGfFkDJhsdFe-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/28472605-4523-4cf8-ac87-c0bfb5cd6bad">
