### ISSUE TITLE
Show a hint for proxy account votes

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3443]
As a user, if I have set a proxy, please set a hint for me so I can know my votes tab are showing votes of my proxy account. Maybe on the red square location.

![Z26KBOeKzJ](https://github.com/opensquare-network/subsquare/assets/2264908/b54ab167-5f4d-4de9-baa1-6cce0934531f)

**Comment by Popoulosss** [comment]
Refer to preimages table, we can filter the votes of my proxy account by toggle

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5727-31295&mode=design&t=r8QkQsYPGp37gJ3o-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/d59af58b-3dd2-45b1-bc3e-712e00fa54ed">

**Comment by Popoulosss** [comment]
Add a hint component in front of the votes table.

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5727-31295&mode=design&t=QW69JyIGKKHynihm-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/30c15a18-b241-4d9c-8622-d54955f95405">

Hint component
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/1627e835-d3ab-4cb1-b25a-f99c3ba43ed8">
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/3e67a740-3006-42c3-a0fd-895f1af610a7">
