### ISSUE TITLE
Add subscription tip component on referenda page panel too

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3445]
![fVxhDXwtnb](https://github.com/opensquare-network/subsquare/assets/2264908/dcb38592-0cf7-4b06-80b0-9d04805906ab)

**Comment by Popoulosss** [comment]
Refer to overview page

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1906-63717&mode=design&t=SMgYdhbWgLHYnr0n-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/8a91cbc1-81db-43e2-953b-584776a5f88b">
