### ISSUE TITLE
Allow deleting a comment if it's created in last 10 mins

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3446]
The comment maybe left by a mistake.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5768-31144&mode=design&t=06hjzIYMCT4vAbWI-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/b4c0aa47-e8bb-4d71-b4e3-d8df7a5cfabd">
