### ISSUE TITLE
Add header to privacy and terms page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3453]
https://polkadot.subsquare.io/terms
https://polkadot.subsquare.io/privacy

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5795-80621&mode=design&t=MxuHS54rwCrck4y1-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/acd7a4b0-e969-4c1d-8820-825a669b5ab3">
