### ISSUE TITLE
Show post index for subsuqare/polkassembly discussions

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3460]
![aeA7gHAhQ3](https://github.com/opensquare-network/subsquare/assets/2264908/3ac67630-49e8-47ea-a0e3-c985c3979052)

**Comment by Popoulosss** [comment]
Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/20afd1f7-5d23-43cc-8061-b2d0c8d0a917">
