### ISSUE TITLE
Show proxied hint for my vote on referendum detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3461]
If we're showing votes of my proxied account, there should be a hint to tell user that the vote is proxied account's.

![X1PgCZSm5t](https://github.com/opensquare-network/subsquare/assets/2264908/7cba4d46-b42d-4bbe-a823-c4d1c79da2f0)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1611-50443&mode=design&t=SMgYdhbWgLHYnr0n-11)

Refer to the hint in votes list
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/5918167d-1f49-42ae-a0fb-2165c07606a7">

Show the proxied hint(simplified) for my vote on referendum detail page
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/423c4f32-0181-49d0-aaf2-c69e14ceee37">
