### ISSUE TITLE
Implement enhance call view on referendum detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3462]
- [x] OpenGov referendum detail page
- [x] Democracy referendum detail page
- [ ] Various collectives motion page

![F7Aq3VmcFX](https://github.com/opensquare-network/subsquare/assets/2264908/5ef9a97e-b44d-40a5-a05a-006beb45fc3d)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=3057-106870&mode=design&t=CbzrhrEGAaNUlZHK-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/6f1f96d0-e939-41bd-97dc-6676d9ef654e">
