### ISSUE TITLE
Warn users to check spam if they can not receive emails

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3470]
Put this warning on the component where user set email.

![O259iMWkSd](https://github.com/opensquare-network/subsquare/assets/2264908/532e66c7-060f-4b33-8d4b-1e38bc9b7f97)

**Comment by Popoulosss** [comment]
- [ ] If user has set the notification email, show the warning notice everytime when user visit notification settings page
- [ ] Warning notice is closable

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1974-63575&mode=design&t=GKOTI2Jnfwaj3EIp-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/fec1eec6-d36d-4b2a-b92c-d0450a4b8180">

**Comment by Popoulosss** [comment]
**Please chech this issue #3540**
