### ISSUE TITLE
Add a link on my on-chain votes to see all history votes

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3472]
We can only see on-chain votes on this page, but in some scenarios, users want to see all history ones when there are managing current votes. So put a link here to help users.

Related #3448.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=3795-68907&mode=design&t=DsfjKA0X8IfPAnHb-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/927b7e3e-8eb9-45b3-8ccc-1377d32e3f1e">
