### ISSUE TITLE
Show bounty/child bounty address on the metadata

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3474]
Every bounty/child-bounty has an address to which other addresses can transfer balances. Showing this address will help users better track the bounty balance history.

**Comment by Popoulosss** [comment]
- [ ] Show the address on the metadata
   - [ ] Bounty
   - [ ] Child bounty

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5852-44490&mode=design&t=5JTc0iMOteoq2yD2-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/557619fc-389e-436f-a10a-41dfe393b40f">
