### ISSUE TITLE
Show bounty balance on bounty detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3475]
As a bounty curator, I want to know how much fund left on a bounty/child-bounty, so I can arrange future child bounty spending.

**Comment by Popoulosss** [comment]
- [ ] Show the bounty balance in the side card
   - [ ] Remaining
   - [ ] Total fund
   - [ ] Child bounties counts (unspent/total) (If there is no child bouties, it is not displayed)

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5852-44490&mode=design&t=5JTc0iMOteoq2yD2-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/28f17caf-c88d-4ffe-810a-96207a06d1e5">
