### ISSUE TITLE
As a governance proposer, I want to manage my various deposits, so I can get them back

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3476]
- [x] Preimages deposit.
- [x] OpenGov decision deposit.
- [x] OpenGov submission deposit. This may not need management, but we should show its status.
- [x] Democracy deposit.
- [x] Treasury deposit.

**Comment by Popoulosss** [comment]
- [ ] Entrance: Overview > My Depost

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6300-34776&mode=design&t=sJ9iXbWcghFwmjz9-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/ea2c55c1-c5e3-4089-96f0-9d05c5df81d0">

**Comment by Popoulosss** [comment]
- [ ] Referenda Decision Deposit
   - [ ] Proposal | Deposit Balance | Status | action: Refund
- [ ] Referenda Submission Deposit
   - [ ] Proposal | Deposit Balance | Status

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/b1b73b07-0a49-4e31-b47d-775ec30e1e4b">

**Comment by Popoulosss** [comment]
- [ ] Democracy Public Proposal
   - [ ] Proposal | Reservation Balance | Status | action: Refund

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/1462d635-d404-486d-a5cb-f23d5f8f591c">

**Comment by Popoulosss** [comment]
- [ ] Treasury Proposal
   - [ ] Proposal | Bond Balance | Status | action: Unbond
- [ ] Treasury Bounty
   - [ ] Bounty | Bond Balance | Status | action: Unbond

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/f33a258d-6b11-4ac3-ac3b-fbec36bcb558">

**Comment by Popoulosss** [comment]
- [ ] Preimages
   - [ ] Hash | Arguments | Depositor Balance | Length | Status | action: Unnote

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/1bdeb094-ead3-48a0-afe3-4ac7253a38d7">

**Comment by Popoulosss** [comment]
#3562

**Comment by Popoulosss** [comment]
[Implement to new overview layout](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7235-55046&mode=design&t=L1p3mWw6H4uAof7w-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/49014830-ad9b-4b46-bff8-2e38bf20c70f">

- [ ] [Referenda](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7235-55409&mode=design&t=L1p3mWw6H4uAof7w-11)
   - [ ] Submission Deposits: Proposal | Deposit Balance | Status | Action: Refund
   - [ ] Decision Deposits: Proposal | Deposit Balance | Status | Action: Refund
- [ ] [Fellowship](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7235-55409&mode=design&t=L1p3mWw6H4uAof7w-11)
   - [ ] Submission Deposits: Proposal | Deposit Balance | Status | Action: Refund
   - [ ] Decision Deposits: Proposal | Deposit Balance | Status | Action: Refund
- [ ] [Democracy](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7707-39850&mode=design&t=L1p3mWw6H4uAof7w-11)
   - [ ] Public Proposal Deposits: Proposal | Reservation Balance | Status | NO ACTION
- [ ] [Treasury](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7707-39170&mode=design&t=L1p3mWw6H4uAof7w-11)
   - [ ] Proposals: Proposal | Bond Balance | Status | NO ACTION
   - [ ] Bouties
      - [ ] Bounty Deposits: Proposal | Bond Balance | Status | NO ACTION
      - [ ] Curator Deposits: Proposal | Bond Balance | Status | NO ACTION
   - [ ] Tips: Proposal | Bond Balance | Status | NO ACTION
- [ ] [Preimages](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7707-39465&mode=design&t=L1p3mWw6H4uAof7w-11): Hash | Arguments | Depositor Balance | Length | Status | Action: Unnote

**Comment by Popoulosss** [comment]
Mobile layout

With action
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/9aa813c2-2f18-4aac-9ef3-ad846acfaf70">

No action
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/0ad7ce08-99f9-44fa-a854-65566afe757b">

**Comment by Popoulosss** [comment]
### Enhance the display of my deposited

- [ ] Show the deposits of `Identity` and `Mulsigs`(If any)

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7235-55046&mode=design&t=zQHBeY2Ids3tOMZU-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/05401e07-b50b-4473-a73a-331dcd0f5ab8">

**Comment by Popoulosss** [comment]
- [ ] Implement `identity` table, need to show both total amount and total value in the title bar

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=8944-40145&mode=design&t=4LkYKV48TbMsgNGM-11)

Web
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/4e2cf53d-70e9-4bab-b672-41ba891dcfef">

Mobile
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/d63e4297-6079-43d5-a8b5-b01944065981">
