### ISSUE TITLE
Show delegation status on profile page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3477]
- [ ] Democracy.
- [ ] OpenGov referenda.
- [ ] Been delegated, total votes and details. We should show details on each track for OpenGov.
- [ ] My delegations to others.

**Comment by Popoulosss** [comment]
- [ ] Show the delegation in profile page

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6326-33675&mode=design&t=rDZa3GAzzTzWJJpk-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/19160ee8-5217-4ae6-96fd-838cb8c610ff">

**Comment by Popoulosss** [comment]
# OpenGov

- [ ] Show the table that user has delegated tracks (track/target to/date/capital.conviction/votes)

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6326-34952&mode=design&t=rDZa3GAzzTzWJJpk-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/c093cd8f-d27c-48a2-b1c1-ef922bae0b8a">

**Comment by Popoulosss** [comment]
## Democracy

- [ ] Delegated votes: show the delegated records
- [ ] Been delegated: show the delegators list

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6338-38155&mode=design&t=rDZa3GAzzTzWJJpk-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/703be867-b848-4eaf-b25f-6b282e7f23ea">

**Comment by Popoulosss** [comment]
Updated @hyifeng

**Comment by Popoulosss** [comment]
Updated @hyifeng 

---

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=10392-115399&mode=design&t=TIpjEO7JWi3VcaRY-11)

Mobile
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/7da0292c-e133-4483-8fbe-b23c73062db0">
