### ISSUE TITLE
We should show prior lock on my votes

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3479]
When all on-chain votes are removed, there may be prior lock, we should show this status to users.

**Comment by Popoulosss** [comment]
- [ ] If there is a prior lock, display in the `Total Locked` cell of votes data panel
   - [ ] Show the prior lock balance
   - [ ] Show the unlock countdown component
   - [ ] Show the prior lock description in the tooltip

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5993-33159&mode=design&t=SMgYdhbWgLHYnr0n-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/b91e8cb7-0ef2-4ef9-a14f-ec8670a42517">
