### ISSUE TITLE
Show empty placeholder for my votes on mobile view

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3499]
Show a empty placeholder when there are no my votes on mobile page view.

![67775DLUNA](https://github.com/opensquare-network/subsquare/assets/2264908/280d2b4f-2f28-4ea5-9df2-1b1d88fa0f46)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6038-75080&mode=design&t=GKOTI2Jnfwaj3EIp-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/0e6addd0-fdb9-4758-96ae-7d1219baa43e">
