### ISSUE TITLE
Make current toast more striking

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3504]
It's not so easy for users to notice toasts. We can make some UI adjustment to make it more striking.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6203-33846&mode=design&t=0XOnyGnfMBXhkEvp-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/9f7d28e7-ee35-4ddf-925a-5806e74a1d04">
