### ISSUE TITLE
Enhance referendum vote view about delegation

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3508]
![G4ye9Lo5dp](https://github.com/opensquare-network/subsquare/assets/2264908/c17f9db1-2f4c-4e80-9d03-53bb578680fb)

**Comment by wliyongfeng** [comment]
![C0AzBPDSEw](https://github.com/opensquare-network/subsquare/assets/2264908/1e14605b-dbdd-4fae-a8e2-ae8714a1ba4c)

**Comment by Popoulosss** [comment]
- [ ] Optimize the delegation descripotion
- [ ] Refer to [my votes record](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1611-50443&mode=design&t=unhyGIlOZk6kyRQW-11), show the votes and delegation info in the `Current Voting`
- [ ] Show identity

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6306-38500&mode=design&t=sJ9iXbWcghFwmjz9-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/338a3ba4-416b-4887-8bb0-44c4ef6d2fe9">
