### ISSUE TITLE
Merge comments from polkassembly and subsquare

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3514]
It's somewhat cumbersome for users to switch between subsquare and polkassembly tabs. It will be better if we can integrate them into a single section.

**Comment by Popoulosss** [comment]
- [ ] Merge comments from polkassembly and subsquare
   - [ ] Remove the toggle switch component
   - [ ] Show the platform icon and display the comment's source in the tooltip
   - [ ] Click on the polkassembly icon to link to the comment on polkassembly
   - [ ] Comment from polkassembly cannot be replied to and more

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=5574-61573&mode=design&t=SMgYdhbWgLHYnr0n-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/d6641f7f-f661-4a60-9023-4178c5f7cf16">

**Comment by 2nthony** [comment]
![image](https://github.com/opensquare-network/subsquare/assets/19513289/b1503570-e112-43d7-9030-5756e1f0d8ee)

I think the deleted content should be dimmed

**Comment by Popoulosss** [comment]
If the comments only from subsquare, the icon is not displayed.
