### ISSUE TITLE
detail page, child bounties tab, table width

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3534]
medium size

![image](https://github.com/opensquare-network/subsquare/assets/19513289/5e022443-f462-41ca-ad7f-6354bd23e7b9)

**Comment by Popoulosss** [comment]
Fixed the width of status column to 120px

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1646-55158&mode=design&t=xhV3tnuGkak5a5Ki-11)

Preivew
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/4565d960-c5ec-42be-a162-9b002b368407">
