### ISSUE TITLE
Enhance view for cookie consent popup

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3551]
v2 design missed

![image](https://github.com/opensquare-network/subsquare/assets/19513289/8cec7df0-c326-4734-8071-7ff1e0427479)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=2326-61089&mode=design&t=hfmNMOls95jBJqoV-11)

**Comment by Popoulosss** [comment]
- [ ] Fixed the cookie consent to the bottom of brower(cover the footer)
- [ ] Optimize the copywriting

We Use Cookies
This site uses cookies to improve your browsing experience , to show you personalized content, to analyze our website traffic.

[Website](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6787-35102&mode=design&t=zJYlUaoEZJUkMJ2D-11)
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/ad8d8dba-9809-4832-b4f3-d4b2f0d7749f">

[Mobile](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1274-61231&mode=design&t=zJYlUaoEZJUkMJ2D-11)
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/15be8bf8-0564-40f8-99d8-a36f260ba641">
