### ISSUE TITLE
Introduce AI summary for posts

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3557]

**Comment by Popoulosss** [comment]
- [ ] Modify the UI
   - [ ] Change the font weight of title of proposal in detail page to `bold`
   - [ ] Remove the divider between the title and accessory info, set the spacing to 16px

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6049-120751&mode=design&t=f8PJyx6JRvZNKwG4-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/4a6f970f-17cb-4bf0-a7e6-b6380b2f1ebc">

**Comment by Popoulosss** [comment]
- [ ] Add the tab component to the content of proposal, named `Content`
- [ ] Implement `AI Summary` item to the tab component
- [ ] When hover over the `AI Summary` item, show the tooltip: Powered by OpenAI
- [ ] Show the annotation when user switches to `AI Summary` mode: Powered by OpenAI
- [ ] If there is no data by ai summary (e.g. proposal content is empty), no need to show `AI Summary` item

Tab component
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a3dc44ab-e81b-4433-91f0-8eb5e36f97cf">

Content mode
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/d47d5f53-9cd2-4d02-9794-3893b181de58">

AI summary mode
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/f28ba597-66dc-484a-87e4-50e7bf137505">

**Comment by Popoulosss** [comment]
### Proposal detail without ai summary

- [ ] If there is no need to implement ai summary, do not show the tab, only keep the divider

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6049-120751&mode=design&t=asHsLpfbkr7WjZ33-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/c80b55eb-04b6-492f-8a97-bba79e19e56d">

---

### Proposal detail with ai summary

- [ ] Show the tab items above the divider
   - [ ] In ai summary mode, show the annotion `Powered by OpenAI`

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6049-120751&mode=design&t=asHsLpfbkr7WjZ33-11)

Content
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/3fc62726-31ad-445c-b35e-9204015551cb">
