### ISSUE TITLE
Show login user balance status on home page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3559]

**Comment by Popoulosss** [comment]
- [ ] Add `Portfolio` tab item to the overview page
- [ ] Show the total balance(transferable, locked)
- [ ] Show the balance list(currently only support the token corresponding to the project)
   - [ ] Including total, transferable, locked, bonded and reserved
   - [ ] If the value of transferable, locked, bonded and reserved is 0, show the `-`

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6701-40190&mode=design&t=DaCFl6BJRU65GOb1-11)

Portfolio
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/f13db98c-96f3-49fd-9ccc-b2cc1cb771ad">
Empty
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/7a742b36-b729-46b7-81cf-af0f4f4a36b6">

---

- [ ] Support transfer token

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6717-72959&mode=design&t=DaCFl6BJRU65GOb1-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/3cf51a49-eefe-4b38-9fa5-a92a1a03cdf5">

---

- [ ] Support receive token

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=6717-72959&mode=design&t=DaCFl6BJRU65GOb1-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/84f61bcb-b746-4149-b38f-cf86ff68b108">
