### ISSUE TITLE
Show how long a OpenGov referendum will begin confirmation

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3578]
As a OpenGov referendum proposer, I want to know when my referendum will begin confirmation by current tally.

![img_v2_b1c2122a-2c2b-446f-8d11-f18357bb889g](https://github.com/opensquare-network/subsquare/assets/2264908/a9a6a497-cb6d-4b81-b4f1-2b1c9199eee0)

**Comment by Popoulosss** [comment]
If the current approval vote reaches the threshold (before the confirmation stage), show how long a referendum will begin confirmation(as time goes on, the support threshold decreases, the support will eventually reach the threshold).

- [ ] Show the estimate time in the popup of threshold curves
- [ ] Show the estimate time in the tally card

[Threshold curves popup](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=4984-34578&mode=design&t=MJybr7SPQQqPy6vj-11)
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/bb2e2ee1-4d40-47b0-b434-2fc907fdcf3d">

[Tally card](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=1611-50443&mode=design&t=MJybr7SPQQqPy6vj-11)
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/4239cb4e-4d16-4ac3-8288-0bf0a957a431">

**Comment by Popoulosss** [comment]
@wliyongfeng 

a: Based on the current voting results, the referenda will start confirmation in **12d 12hrs**.
b: The referendum is expected to be confirmed in **12d 12hrs** based on the current voting results.
