### ISSUE TITLE
As a proposer, I want to create a OpenGov referenda proposal on subsquare

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3613]
- [x] #3626
- [x] Support creating a OpenGov referendum.
- [x] Add a step guide for a new OpenGov referendum. The first step is creating preimage, and the second is creating a proposal.

**Comment by Popoulosss** [comment]
### Create a new preimage

- [ ] Refer to the #3626

**Comment by Popoulosss** [comment]
### Submit a new proposal with existing preimage hash and length

[For submitting from `all referenda`](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7481-52070&mode=design&t=OTLaRGxabCniA1MN-11). User needs to:
- Select track
- Fill the preimage hash and length
- Set enactment blocks(after delay or at block)

<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/cc3352e5-e79b-44bc-bad4-955e4208436d">

---

[For submitting from `track`](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7481-52070&mode=design&t=OTLaRGxabCniA1MN-11). The track is selected by defualt(current track), but user still can change it, and user needs to:
- Fill the preimage hash and length
- Set enactment blocks(after delay or at block)

<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/0ac85c07-7072-44f5-a1c8-27595ac69a90">

---

[For submitting from `democracy`](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7472-51598&mode=design&t=OTLaRGxabCniA1MN-11). User needs to:
- Fill the preimage hash
- Set locked balance

<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/aa25e869-7da1-4bf0-b22c-62d06061692f">

**Comment by Popoulosss** [comment]
- [ ] After the user submitts a new proposal successfully, the page will redirect to the proposal detail page

Preview
(TBD)
