### ISSUE TITLE
Show treasury state on subsquare home page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3705]
- For dotreasury implemented chains
- Data: current balance, to be awarded, next burn, spend period, treasury related OpenGov proposals info

**Comment by Popoulosss** [comment]
- Show the counts of referenda and fellowship(only in Kusama for now) in the individual cell, with the format of `active / total`
- Show the treasury stats in the panel, refer to [dotreasury](https://polkadot.dotreasury.com/#/)
   - Available: token and fiat money
   - To be awarded: token and fiat money
   - Next burn: token
   - Spend period: modify the layout and scale up the countdown component

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7219-48074&mode=design&t=LfZqCP6hP8aSfBlb-11)

Web
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/521bc4b8-14ce-4f8a-8f7d-855f2ab89d03">

Mobile
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/cd8a719d-0cf5-4571-a3a9-30f3ad197d2b">

**Comment by Popoulosss** [comment]
Updated @2nthony 

- Show the same data and format in the Treasury

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/9a389070-0a63-4a1c-98ca-82fd21731ab4">
