### ISSUE TITLE
account multisig sign status

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3712]
- [ ] Change the tooltip content for `unsign` icons: You didn't sign this multisig
- [ ] Change the tooltip content for `approved` icons: You approved this multisig

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7272-35946&mode=design&t=TBrn5bQfDS38Pz4F-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/d5cb72a7-f98f-49bd-a48e-cc73da803028">

**Comment by wliyongfeng** [comment]
Mark this commit e66bfc8f3540773e324bbb863b36567c52acc798 which can be reused in future implementation. We temporarily removed the button for sign multisig.
