### ISSUE TITLE
Support retract tip action

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3731]
Code is [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/tips/src/lib.rs#L300-L313). Only tip finder can call it.

@Popoulosss we need design a retract button.

**Comment by Popoulosss** [comment]
For proposer, show the text `As a treasury tip proposer, you can **Retract Tip**`, highlight the `Retract Tip`

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=2845-66916&mode=design&t=AC0lcEbIrnADton5-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/8f357549-969b-4b5f-a83b-575cd60cadd1">
