### ISSUE TITLE
font issues of comments on profile page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3788]
Check here: https://polkadot.subsquare.io/user/12s6UMSSfE2bNxtYrJc6eeuZ7UxQnRpUzaAh1gPQrGNFnE8h/posted/comments

![HJY2qysrDO](https://github.com/opensquare-network/subsquare/assets/2264908/c5df1610-f301-45b5-9af7-3ea158e3051d)

Please confirm it @Popoulosss .

**Comment by Popoulosss** [comment]
Updated @2nthony 

- Change the font style of comment text to: font size 14px, line height 20px

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a96a715b-e7b9-4007-a069-26ffbbac6f94">
