### ISSUE TITLE
Show polkadot collectives RFCs on subsquare collectives

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3825]
Api: https://api.github.com/repos/polkadot-fellows/RFCs/issues

Issues: https://github.com/polkadot-fellows/RFCs/issues

**Comment by Popoulosss** [comment]
- Show RFCs in the discussions panel, and in the first place
- Show the issue index and title, and last activity
- Click `View All` visit the site https://github.com/polkadot-fellows/RFCs/issues

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=10473-138058&mode=design&t=yRn0pmJooaV6eEoX-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/989dbe95-5b43-42c2-9ae6-ccd180d7ba33">
