### ISSUE TITLE
As a user, I want to know that I have set a proxy, so I know all the txs are on behalf of the proxied account

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#3848]
We need a design on home page to inform user this message.

@Popoulosss design required.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7121-45610&mode=design&t=ztvdzIBsOqny4YBj-11)
