### ISSUE TITLE
Comment on behalf of proxied account

### ISSUE THREAD

**Issue by kianenigma** [opensquare-network/subsquare#3909]
Is it possible to comment on behalf of my proxied account? Ideally, I want to only import my proxy account into the app and work with that. But ideally, I want my proxied account, which has identity, to be the one that is being displayed. 

Possibly this is a very niche use case, as most people don't have such a setup and the proxy account is the one that has identity as well.

**Comment by kianenigma** [comment]
One solution seems to use normal web2 login, but I have already created accounts with my web3 addresses and cannot link them anymore to the web2 login.

**Comment by wliyongfeng** [comment]
I think this is necessary. Currently we support only submitting extrinsics on behalf of proxied account. Ideally after users setup the the proxied account info, we should prompt users to choose between proxy and proxied accounts when submitting extrinsics or commenting. 

This may bring extra work that we'd have to check the on-chain proxied info for every proxied account comment request. We will put this in plan though.

Web2 login will be finally removed in our long-term plan and subsquare will be a web3 product, data will be decentralized by [sima-spec](https://github.com/opensquare-network/sima-spec).

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=25648-10324&node-type=frame&t=ZuA1lWKNq7yqUCLi-11)

For the users who have set up proxied account(s)
- Implement a [split style](https://atlassian.design/components/button/split-button/examples) to comment button
- User can choose `Comment as a proxy` from the dropdown menu, then select proxied account(s) in the dialog

**Comment by wliyongfeng** [comment]
@kianenigma Comment on behalf of a proxied account works on [polkadot subsquare](https://polkadot.subsquare.io/) now. We will enable it on [kusama](https://kusama.subsquare.io/) and [collectives](https://collectives.subsquare.io/) soon.

**Comment by kianenigma** [comment]
Thank you guys! appreciate the support.
