### ISSUE TITLE
Implement delegation prompt on overview page

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4016]
- Add a prompt to the overview page
- User can quickly access the delegation page by clicking `here`
- User can temporarily close the prompt for 7 days, the prompt will appear again after being turned off for 7 days 

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=7219-48074&mode=design&t=kFN2khdHGcWxz5pJ-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a66d12f3-6a54-44e5-a35d-a1a3cf9c0023">

**Comment by wliyongfeng** [comment]
14 days is better.
