### ISSUE TITLE
Sort delegates by delegated votes/delegators/participation rate

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4028]
There should be select box and we can sort delegates by:
- Delegated votes
- Delegators
- Participation rate

Please give figma link @Popoulosss .

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=13522-76721&mode=design&t=cuoFRVZfvvxJsQcv-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/40738e5a-e4c9-4038-aafa-07a8a38394b9">
