### ISSUE TITLE
Support publish announcement through SIMA spec

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/subsquare#4053]

**Comment by Popoulosss** [comment]
- Change the subtitle `Short Bio` to `Short Description`, and make `Short Description` required
- Add `isOrganization` input item (checkbox)
- Add a prompt for Sima Spec
- Add loading status for `Saving` and `Signing`

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=14034-44638&mode=design&t=3eKrhyZOxFnOYupk-11)
