### ISSUE TITLE
Design collectives salary system members page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4055]
- Show current salary cycle index.
- We should see who are inducted already.
- We should see who have already registered in current cycle.
- Show members' active salary and passive salary.
- Show members' last active cycle index.
- We should see their state.
  - Nothing.
  - Registered(Balance): balance means the salary. 
  - Attempted: `Attempted { registered: Option<Balance>, id: Id, amount: Balance }`.
- Add a filter component to filter current cycle registered ones and others.

---------
Actions:
- Induct on summary footer.
- Register on the active cycle panel.
- payout/payout_other on the active cycle panel.

---
Summary:
- Total
- Registered
- Not Inducted

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=15054-125138&mode=design&t=eRJs2bI3eIDmyMGB-11)

Perview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/b83178f5-bdb8-4ddb-bd41-74d254be294e">

---

- For the action
   - induct -> resigister -> payout
   - induct & resigister -> payout

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a811e229-b63c-4be3-a95f-791e10d0f13a">

---

- Payout dialog
   - payout to myself
   - payout to other address

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/57309ad3-aaad-4924-9ed7-d944dbc672d7">
