### ISSUE TITLE
As a voter, I want to see all referenda I haven't voted

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4068]

**Comment by Popoulosss** [comment]
- Modify the hierarchy of the tab component
- Display the list of proposals that have not been voted on

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=15348-18132&mode=design&t=XXhwPWNvDavHYir7-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/e69dddc9-e93e-4f0d-b7b0-0477cd369ef2">

**Comment by Popoulosss** [comment]
Please review the design draft @wliyongfeng
