### ISSUE TITLE
Add decentrilized voices to votes bubble

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4072]
Display the decentrilized voices below the nested votes bubble
- Show the votes of the decentrilized voices, aye and nay
- Click icon to view the decentrilized voices detail

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=15784-22875&mode=design&t=xK7en0BMpGTnmH6d-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/745faef1-0168-4388-b40b-33c0cf3eeef0">

**Comment by wliyongfeng** [comment]
[DV round 1 announcement](https://medium.com/web3foundation/decentralized-voices-round-1-candidates-announced-23d9a800b260)
