### ISSUE TITLE
Show the `DV` tag on comments panel and votes records

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4117]
- [x] [Comments](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=15828-88068&mode=design&t=BYiPzqvjKSpaRSW7-11)

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/52577f28-2342-4462-8a44-44facdb2004c">

---

- [x] [Votes records](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=4789-36795&mode=design&t=BYiPzqvjKSpaRSW7-11)

<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/ee814c7c-72af-4bb9-9923-a45d347d76bb">

**Comment by wliyongfeng** [comment]
@2nthony Notes:
1. Only show DV tag on OpenGov referendum detail page.
2. Only show on nested votes popup.
