### ISSUE TITLE
Incorrect challenge answer received

### ISSUE THREAD

**Issue by carlosala** [opensquare-network/subsquare#4127]
Hi! I was trying to verify my identity with the challenge to the wallet ("signRaw" feature), and I was getting `Incorrect challenge answer`.
I debugged it and discovered that the signer I'm using (Ledger) returns the signature with a `0x00` prefix. Then, the signature is 65 bytes long.
I suppose that in the API you're not accepting this version, but it's in general accepted in Polkadot. [Here](https://github.com/polkassembly/polkassembly/blob/main/src/auth/utils/verifySignature.ts) you have an example of how Polkassembly verifies the signature, underneath [Polkadot-JS takes into account this prefix](https://github.com/polkadot-js/common/blob/f23f0944a85a6ddff72a8cd5866e85fd88edea39/packages/util-crypto/src/signature/verify.ts#L89-L113). In general, in the [Polkadot Spec](https://spec.polkadot.network/id-extrinsics#defn-extrinsic-signature) is specified that extrinsics are prefixed to make the receiver know about the kind of signature used.
Thanks!

**Comment by wliyongfeng** [comment]
@carlosala Thanks for this issue. We also use `signatureVerify` from `@polkadot/util-crypto`. Can we talk more details in telegram: https://t.me/wliyongfeng?

**Comment by carlosala** [comment]
This has been solved, now Ledger users can login in Subsquare! 🎉 
Thanks for the responsiveness! 🎉
