### ISSUE TITLE
Multiple EVM wallet support. Check rainbowkit.

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4136]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=14506-19586&mode=design&t=sss0ZnUZGsXZ8y6j-11)

**For projects that**

---

Support both EVM and Substrate addresses
- [ ] Add an EVM option to connect wallet dialog
- [ ] Add arrow icon to the EVM option, click to show a list of evm wallets
- [ ] EVM wallet support, refer to [rainbowkit](https://www.rainbowkit.com/docs/introduction), [evmkit](https://docs.evmkit.com/introduction)
   - [ ] MetaMask
   - [ ] OKX wallet
   - [ ] Phantom
   - [ ] Base Wallet
   - [x] etc.
   - https://github.com/WalletConnect/EIP6963/blob/master/src/utils/injected.ts
   - https://github.com/rainbow-me/rainbowkit/tree/main/packages/rainbowkit/src/wallets/walletConnectors

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/212ec0ff-7f2e-4a0c-9a14-a580b91bc424">

---

Only support EVM addresses, e.g. [Darwinia2](https://darwinia2.subsquare.io/)
- [ ] Show EVM wallet options dialog direclty

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/ab0d5c10-9ce5-446a-91b1-39ba7672ce46">

WalletConnect
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/255bd68e-e66d-4c82-8815-cb34d2ada513">

**Comment by ImdioR** [comment]
Nice
please add walletconnect too!
Thanks.
