### ISSUE TITLE
As an user, I want to set my avatar

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4153]
Check SIMA spec [avatar section](https://github.com/opensquare-network/sima-spec/tree/main/avatar).

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=17465-38709&mode=design&t=0rviIPeAXTGN9PZR-11)

---

- [ ] Add actions to the address panel in settings page. If address has set identity, show a link to statescan

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/97c26968-dc65-4266-9628-7d72588cc848">

---

- [ ] User can upload image, save and publish through SIMA spec in the `Edit Avatar` dialog

Dialog
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/95af0e5a-f5ea-44ab-a7d5-c71daeacef5a">

**Comment by Popoulosss** [comment]
- [ ] Add a prompt in the account panel to set the user avatar

**Comment by Popoulosss** [comment]
Fix ui

---

- [ ] Remove the padding bottom

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/3e4d8dd1-0e32-4500-a2e8-0bae5de61b56">
