### ISSUE TITLE
As a collective member, I want to set myself to be active or unactive

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4155]
Should be on fellowship [core page](https://collectives.subsquare.io/fellowship/core).

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=9686-81171&mode=design&t=SuD21nsrYJT0LsBs-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/b4437ce7-bb3a-4818-a6bd-5a6db71a709d">
