### ISSUE TITLE
Support connected users to bump expired cycle

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4157]
When the cycle's countdown to the end, users can bump it that turn the status `Ongoing` to `Closed`

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=17446-33181&mode=design&t=0rviIPeAXTGN9PZR-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/4388f84f-cc7e-4fb6-b249-bb1455f00ef2">

**Comment by Popoulosss** [comment]
Once the expored cycle has been bumped, start the next cycle? @wliyongfeng

**Comment by wliyongfeng** [comment]
> Once the expored cycle has been bumped, start the next cycle? @wliyongfeng

Yes, the next cycle will start.
