### ISSUE TITLE
Add escrow statistics for interlay/kintsugi

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4164]
- [ ] Current status
- [ ] History data trend chart

Data:
- total supply
- total staked balance
- total staked account

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?type=design&node-id=17588-128327&mode=design&t=wgGqWiydMSIcaKtr-11)

---

[Interlay](https://interlay.subsquare.io/)

---

[Kintsugi](https://kintsugi.subsquare.io/)
