### ISSUE TITLE
Add `system#remark` to referenda templates

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4205]
In `WishForChange` track, communities propose `system#remark` call. We can add this template to referenda templates to help users with this process.

@Popoulosss We need a simple design for this issue.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=18290-7100&t=C7pCJPpll74QY9mC-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a04fdcab-b06a-47c4-8ac7-673f923cd50f">
