### ISSUE TITLE
Can't bond telegtram notification bot @subsquare_bot

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4251]
Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/d9889a84-5403-48ba-8303-12f25b8803d2">

**Comment by kopeboy** [comment]
How is this completed? How to get Subsquare notifications on Telegram? If you message `/start` to @subsquare_bot nothing happens..

**Comment by wliyongfeng** [comment]
Hey @kopeboy , please visit subsquare notifications setting page. You can see telegram setting steps on the channels section.
![img_v3_02cr_b3e37481-4792-438b-9c63-ae52a08a5e1g](https://github.com/user-attachments/assets/b320116f-b5d8-4498-8c32-a612fd1f0c56)
