### ISSUE TITLE
Implement SIMA discussion

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/subsquare#4264]
Use SIMA discussion when it is enabled in chain settings

- [x] Implement SIMA discussion, since posting content now requires signature, users without address may not be able to create new discussion.
- [x] Append a discussion

**Comment by Popoulosss** [comment]
Append a discussion process

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19424-155314&t=O6SBOuPKHk8mgvZS-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/c6fe977e-027c-4fcc-97f1-6a16e5511245">

---

Appendant
- *index
- content
- timestamp

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/98d5b605-e5a0-47ec-b844-ef22d50bbc40">
