### ISSUE TITLE
Long identity view

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4278]
On delegation page.

![1jxiKn1Fdc](https://github.com/opensquare-network/subsquare/assets/2264908/c6764b04-a9ca-4700-a9ae-e6699b43539c)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19281-12580&t=tnlttuhx5mlbdraC-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/b29bea54-a157-436c-9fd7-7d9103bc5842">
