### ISSUE TITLE
Improve Referenda generation for Fellowship tracks

### ISSUE THREAD

**Issue by bkchr** [opensquare-network/subsquare#4282]
![image](https://github.com/opensquare-network/subsquare/assets/5718007/c0b8ad61-60f4-4df4-81f2-354e5b1d2c3b)

It should be quite clear on what kind of proposal I want to open at this track. It should basically ask me for which account I want to open the proposal. Currently it asks me if I want to create a pre-image or already have a pre-image hash. 

I would expect that the flow is the following:

- Click `create proposal`
- Ask for the account/show accounts that could be promoted to rank X
- Provide checkboxes for `place deposit`
- Submit. This should upload the pre-image, create the referendum automatically, vote yes (opening and voting No makes not that much sense? But could maybe be some pre-selected checkbox above) and optionally place the decision deposit.

**Comment by wliyongfeng** [comment]
As what we did on polkadot, we can add several proposal templates for collectives fellowship.
- Promote a member to a rank.
- Retain a member at a rank.

> vote yes (opening and voting No makes not that much sense? But could maybe be some pre-selected checkbox above) and optionally place the decision deposit.

Yeah, voting yes should be optional, not every proposer want to vote yes for proposal created. Placing the decision deposit is a little different, and it's difficult to put this call in a batch call with submission, cause we won't know the referendum index to be created. We can estimate the index or we can ask another sign from user to submit another call, but the implementation will be more complex.

**Comment by bkchr** [comment]
> Yeah, voting yes should be optional, not every proposer want to vote yes for proposal created.

Discussable. I mean otherwise I would not create a referenda, if I'm not behind it.

**Comment by wliyongfeng** [comment]
> I mean otherwise I would not create a referenda, if I'm not behind it.

I got you, but it's not always the case. An example in gov1, Raul, many times act as a moderator, will create a council motion, but he may vote nay. Creating a proposal is just making it possible for all voters(councilors) to give a decision. 

Getting back to fellowship, when a member(A, rank < 3) submit an evidence, I believe another member(B, rank >=3) should create a promote/retain proposal for A, considering A can't create this proposal for himself. In this case, B should create this proposal even, but he may vote nay.
