### ISSUE TITLE
Induct UI: It is not clear that the field it editable

### ISSUE THREAD

**Issue by bkchr** [opensquare-network/subsquare#4283]
![image](https://github.com/opensquare-network/subsquare/assets/5718007/78f9b9fa-2af2-4313-ac14-bb389a999e2f)

It was not really clear to me that the field is editable. I just found out by accident. Would be nice if this is made more prominent.

**Comment by Popoulosss** [comment]
Show the input status by default

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/9426b5d6-9402-4cbd-b2d2-40be64f918b1">
