### ISSUE TITLE
fellowship/core page showing incorrect "promotion period" for Rank 1 members

### ISSUE THREAD

**Issue by acatangiu** [opensquare-network/subsquare#4306]
## Context

https://github.com/polkadot-fellows/Evidences/pull/24#discussion_r1650748569

`fellowshipCore.params: PalletCoreFellowshipParamsType` storage:
```
{
  ...
  minPromotionPeriod: [
    0
    2,629,800
    2,629,800
    2,629,800
    2,629,800
    2,629,800
    2,629,800
    1,314,900
    2,103,840
  ]
  ...
}
```

Code for [target rank converted to index](https://github.com/paritytech/polkadot-sdk/blob/d5fe478e4fe2d62b0800888ae77b00ff0ba28b28/substrate/frame/core-fellowship/src/lib.rs#L570) converted to period -> only rank0->rank1 has `0` min period.

## Issue

Subsquare UI is incorrectly showing `Promotion Period: 100%` for all current Rank 1 members.

E.g. member with less than 1 year in rank 1:
![Screenshot 2024-06-24 at 14 11 45](https://github.com/opensquare-network/subsquare/assets/31917973/6e2a8e1a-5015-4367-9257-8862bb06775b)

**Comment by wliyongfeng** [comment]
Hey @acatangiu , thanks for this issue. I'm confused with this sentence `only rank0->rank1 has 0 min period.` Is it that all rank 1 members has index 0, so all rank 1 members have a min promotion period 0?
