### ISSUE TITLE
Show on-chain evidence info on a fellowship referendum for promotion

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4311]
There maybe some cases:
1. If no evidence, show a info to tell we can't find evidence on chain.
2. If there is a evidence IPFS link but we can not load the corresponding content, show IPFS link but tell we can't load the content.
3. Show IPFS link and content if we can get either of them.

**Comment by Popoulosss** [comment]
Refer to the display of `Remark` row, add `Evidence` row to the call table

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19580-15446&t=84kWn2YxCQkdCkMM-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/29137b1f-9d01-4dfa-933e-518a092d850d">

**Comment by Popoulosss** [comment]
Display the type of evidence before the subtitle "Evidence": Promotion or Retention

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/4011ecc2-7491-44f1-83e3-5dc6221d532b">

**Comment by Popoulosss** [comment]
@2nthony 
Implement a loading effect and no evidence state to evidence content

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19659-140714&t=0t7NUxK9ukqBMJEK-11)

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/2312bc96-4ae1-42c9-be8c-da0d2bf78457">
