### ISSUE TITLE
Support polkadot ambassador business

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4314]
- [x] [Add ambassador members page](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19643-108320&t=p670XsQnXTBqRJzQ-11)
- [x] [Core page members](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19659-135794&t=p670XsQnXTBqRJzQ-11)
- [x] Core page actions
- [x] salary page
	- [x] import me button
	- [x] cycles page
		- [x] current cycle panel
		- [x] history cycles list
	- [x] cycle detail page
		- [x] my salary status
		- [x] actions button
			- [x] bump button
			- [x] register button
			- [x] payout button
		- [x] tabs list
	- [x] claimants page
	- [x] feeds page

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19414-150923&t=84kWn2YxCQkdCkMM-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/6d894a57-201c-40b7-b562-9118a7752273">
