### ISSUE TITLE
Show fellowship related business on profile page.

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4319]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20890-14033&t=gWyS5h2iQNo0axSw-11)

- Add the `Fellowship` tab to profile
- Show the member info
   - status
   - rank, period of demotion/promotion or offboard timeout(candidate)
   - active salary
   - passive salary

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/80ccb88d-60ad-4afe-8a6f-2c34b67ae547">

---

- Core
   - timeline
   - evidence

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/3d180d01-e9f5-4417-80af-aeeb2f00c41e">

---

- Salary
   - total
   - timeline
   - payments

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/27aec88b-8d56-4806-993e-81374572e84a">

**Comment by Popoulosss** [comment]
*On collectives, the rank tag can be a suffix to the username

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19643-108945&t=p670XsQnXTBqRJzQ-11)

Rank tag
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/be4c2094-32a7-48ab-864b-acc4dbcef158">

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/57debff9-4abb-43d7-8963-540ac67c9f22">

**Comment by wliyongfeng** [comment]
@2nthony 

Example evidence API:
https://collectives.subsquare.io/api/fellowship/core/evidences?who=12gMhxHw8QjEwLQvnqsmMVY1z5gFa54vND74aMUbhhwN6mJR

Other query params:
- page
- page_size

**Comment by wliyongfeng** [comment]
Fellowship profile statistics example API:
https://collectives.subsquare.io/api/fellowship/statistics/users/14DsLzVyTUTDMm2eP3czwPbH53KgqnQRp3CJJZS9GR7yxGDP

```json
{
  "totalPaid": "115000000000",
  "promotionTimes": 0,
  "demotionTimes": 0,
  "retentionTimes": 1
}
```

[Figma](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20917-133246&t=BIOpjz6XyNInktBv-0)
