### ISSUE TITLE
Fellowship statistics

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4329]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19659-170416&t=sUmyHbr9gvmW5wda-11)

**Comment by wliyongfeng** [comment]
Fellowship statistics salary cycles API:

https://collectives.subsquare.io/api/fellowship/statistics/salary/cycles

Fellowship statistics salary members rank API:

https://collectives.subsquare.io/api/fellowship/statistics/salary/members

**Comment by wliyongfeng** [comment]
Steps:
1. Init fellowship statistics page
2. Implement expenditure statistics

Tips:
- No need to do SSR.

**Comment by wliyongfeng** [comment]
@leocs2417 @2nthony  Fellowship statistics salary by ranks API:

https://collectives.subsquare.io/api/fellowship/statistics/salary/ranks

**Comment by Popoulosss** [comment]
@wliyongfeng 

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19659-170416&t=Sd9ZMiytnrAYlAeF-11)

Felloship members
- Pie chart: rank distribution
- data panel: promotion times, retention times, demotion times, total active salary, total passive salary

Preview
<img width="320" alt="image" src="https://github.com/user-attachments/assets/e789dab8-115d-498b-b500-0cc555a6d4d8">

**Comment by wliyongfeng** [comment]
@leocs2417 API to get membership promotion/demotion/retention times:

```
https://collectives.subsquare.io/api/fellowship/statistics/membership/times
```
