### ISSUE TITLE
Add templates on preimages page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4331]
As an user, we want some quick start template on preimages page so it'll be very easy for me to create some kinds of preimages like spend stable treasury, etc.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19888-48102&t=QlcUh0oxqOCMR8Aq-11)
