### ISSUE TITLE
Support for PolkaGate Snap

### ISSUE THREAD

**Issue by AMIRKHANEF** [opensquare-network/subsquare#4349]
We would like to propose adding support for PolkaGate Snap in MetaMask. PolkaGate Snap is a snap for MetaMask that enhances its functionality by integrating with the Polkadot ecosystem.

**Benefits:**

- Enables MetaMask users to interact with Polkadot-based dApps.
- Provides a seamless experience for users across different blockchain networks.
- Enhances the interoperability of MetaMask with the Polkadot ecosystem.

The integration involves making changes across two different repositories, and it is crucial that the pull requests be merged in a specific order.

**Details:**

1. **First pull request:** This pull request will include adding the logo for PolkaGate Snap.
- Repository: `opensquare-network/icons`
- Pull request Description: Add PolkaGate Snap logo.
- [Link](https://github.com/opensquare-network/icons/pull/7)

2. **Second pull request:** This pull request will include the necessary changes to support PolkaGate Snap functionality.
- Repository: `opensquare-network/subsquare`
- Pull request Description: Support for PolkaGate Snap.
- [Link](https://github.com/opensquare-network/subsquare/pull/4348)

**Important Note:** The first pull request (adding the logo) must be merged before the second pull request (support changes) can be merged.

Your assistance in reviewing and merging these pull requests in the correct order would be greatly appreciated. If there are any questions or additional information required, please feel free to reach out.

Thank you for your support.

**Comment by 2nthony** [comment]
@AMIRKHANEF should `polkagate snap` button display in all chains that SubSquare supported? or just display in specified chains(e.g. polkadot, kusama, westend)?

because we have some EVM chains supported, for hydration(hydradx) example:
the `EVM` button only displayed which chains support EVM
<img width="577" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/f29b3f2a-4710-4672-a983-14efb28c0577">

**Comment by Nick-1979** [comment]
First of all, thank you for merging our PR.

Polkagate Snap currently supports only substrate-based chains that provide endpoints as listed in Polkadot JS apps. In the upcoming release, we have added a 'sign with metadata' feature. This means that any other substrate-based chains, even those without provided endpoints, can enable the Snap to sign transactions by uploading their metadata. 

We do not support EVM-based chains within the Snap, but I believe Metamask itself may have native support for them. However, we may consider adding support for EVM-based chains to the Snap in the future.

**Comment by 2nthony** [comment]
ok, we'll hide the snap button in EVM-based chains.

**Comment by AMIRKHANEF** [comment]
Thank you so much, we really appreciate it.
