### ISSUE TITLE
Can’t claim the treasury payout via Ledger in Subsquare.

### ISSUE THREAD

**Issue by pzshine** [opensquare-network/subsquare#4352]
1. I updated the Polkadot App on Ledger to version (v100.0.5).
2. I tried to claim it via Ledger using both the Talisman wallet and the Polkadot.js extension on Chrome.
3. It keeps showing an error when I try to sign.

Tailsman: 
<img width="395" alt="image" src="https://github.com/opensquare-network/subsquare/assets/17017699/3fdf1bd3-44d9-40cf-ae14-dd5a2d60b198">

Polkadot.js:
<img width="562" alt="image" src="https://github.com/opensquare-network/subsquare/assets/17017699/ac1cac65-809c-4027-8948-a681f25b6d29">

How can I solve this problem?

Thank you.

**Comment by wliyongfeng** [comment]
@pzshine Can I know which button you clicked on subsquare? I want to confirm the process. 
1. You connect your ledger to tailisman/polkadot.js extension.
2. You connect subsquare with talisman/polkadot.js extension.
3. You click a button on subsquare, but talisman or polkadot.js extension has an error when you tried to sign the extrinsic.

Is this process correct?

**Comment by pzshine** [comment]
> @pzshine Can I know which button you clicked on subsquare? I want to confirm the process.
> 
> 1. You connect your ledger to tailisman/polkadot.js extension.
> 2. You connect subsquare with talisman/polkadot.js extension.
> 3. You click a button on subsquare, but talisman or polkadot.js extension has an error when you tried to sign the extrinsic.
> 
> Is this process correct?

You're right.

**Comment by pzshine** [comment]
> So which button please, and did you try polkadot apps, is it works there?

I clicked on these buttons. 

<img width="345" alt="image" src="https://github.com/opensquare-network/subsquare/assets/17017699/045c6179-219e-4b1e-a0c3-03f5fa935d3e">
<img width="431" alt="image" src="https://github.com/opensquare-network/subsquare/assets/17017699/558f4998-81f0-4239-b371-381fd160dbbb">

Which Polkadot apps is it? 
Do you mean [this one](https://polkadot.js.org/apps/#/accounts)? If it is, can you guide me on how to claim it via Polkadot apps?

**Comment by wliyongfeng** [comment]
You can add my telegram account, so we can talk about more details: https://t.me/wliyongfeng
