### ISSUE TITLE
Implement AssetHub management

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4354]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20040-141770&t=zFpFh71TCnqMJe9c-11)

### Color

**AssetHub Polkadot (Statemint)**
```
export const light = {
  dark: false,
  // polkadot assethub
  theme100: "rgba(230,0,122,0.10)",
  theme300: "rgba(230,0,122,0.40)",
  theme500: "rgba(230,0,122,1)",
  navigationBg: "rgba(40,18,62,1)",
  navigationActive: "rgba(255,255,255,0.04)",
  navigationBorder: "rgba(255,255,255,0.08)",
};

export const dark = {
  ...light,
  dark: true,
  // polkadot assethub
  theme100: "rgba(230,0,122,0.10)",
  theme300: "rgba(230,0,122,0.40)",
  theme500: "rgba(230,0,122,1)",
  navigationBg: "rgba(33,36,51,1)",
  navigationActive: "rgba(38,41,56,1)",
  navigationBorder: "rgba(39,42,58,1)",
};
```

**AssetHub Kusama(Statemine)**
```
export const light = {
  dark: false,
  // kusama assethub
  theme100: "rgba(230,0,122,0.10)",
  theme300: "rgba(230,0,122,0.40)",
  theme500: "rgba(230,0,122,1)",
  navigationBg: "rgba(0,0,0,1)",
  navigationActive: "rgba(255,255,255,0.10)",
  navigationBorder: "rgba(255,255,255,0.12)",
};

export const dark = {
  ...light,
  dark: true,
  // kusama assethub
  theme100: "rgba(230,0,122,0.10)",
  theme300: "rgba(230,0,122,0.40)",
  theme500: "rgba(230,0,122,1)",
  navigationBg: "rgba(33,36,51,1)",
  navigationActive: "rgba(38,41,56,1)",
  navigationBorder: "rgba(39,42,58,1)",
};
```

**AssetHub Westend(Wesmint)**
```
export const light = {
  dark: false,
  // westend assethub
  theme100: "rgba(239,72,106,0.10)",
  theme300: "rgba(239,72,106,0.40)",
  theme500: "rgba(239,72,106,1)",
  navigationBg: "rgba(255,255,255,1)",
  navigationActive: "rgba(246,247,250,1)",
  navigationBorder: "rgba(235,238,244,1)",
};

export const dark = {
  ...light,
  dark: true,
  // westend assethub
  theme100: "rgba(239,72,106,0.10)",
  theme300: "rgba(239,72,106,0.40)",
  theme500: "rgba(239,72,106,1)",
  navigationBg: "rgba(33,36,51,1)",
  navigationActive: "rgba(38,41,56,1)",
  navigationBorder: "rgba(39,42,58,1)",
};
```

**Comment by wliyongfeng** [comment]
- [ ] Add assets menu @hyifeng

**Comment by Popoulosss** [comment]
@hyifeng updated

Files
[sns.zip](https://github.com/user-attachments/files/16142149/sns.zip)

**Comment by Popoulosss** [comment]
Add a asset table to profile page

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20272-705&t=kq9z5nwIxZEo88pc-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a158b21d-0ab4-43fd-bc44-31413728c630">

**Comment by Popoulosss** [comment]
@hyifeng updated

Add `ID` column to asset table, the native token(DOT) shows `-`

**Comment by Popoulosss** [comment]
@hyifeng updated

---

Implement a number display format
- integer number, color `textPrimary`
- fixed display 4 decimal places, color `textTertiary`
- when the value is 0, show `-`

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20169-161759&t=VFe9RfWgRYmgoMgX-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/fdbc4d21-7382-435a-b54e-1442baab1b81">

---

- Add `Transferable` column
- Remove `Frozen` column

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/4dbfafe5-c608-4844-a254-bd5c645a45e4">

---

Implement the number display format to `Transfer` dialog

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20169-166627&t=VFe9RfWgRYmgoMgX-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/ec2a3eb9-4b91-42a6-af5d-333611e94812">
