### ISSUE TITLE
Unexpected Behavior with PolkaGate Snap when only MetaMask is available to connect

### ISSUE THREAD

**Issue by AMIRKHANEF** [opensquare-network/subsquare#4399]
## Summary
The `useInjectedWeb3` hook currently does not handle the scenario where only MetaMask is available on the browser, causing PolkaGate Snap on MetaMask to become disabled. This is not the expected behavior.

## Steps to Reproduce
1. Try to connect with PolkaGate Snap when only MetaMask is available on your browser.
2. Observe that PolkaGate Snap becomes disabled.

## Expected Behavior
PolkaGate Snap should remain enabled even when no other wallets are available.

## Solution
Modify the `useInjectedWeb3` hook to check for `window.ethereum?.isMetaMask` in addition to `window.injectedWeb3`.

**Comment by 2nthony** [comment]
hi, we refactored the snap button to a standalone file for more easy to maintain, you can see it #4404, also apply the solution you provided.

but we still fixing some unexpected issues.

**Comment by AMIRKHANEF** [comment]
> hi, we refactored the snap button to a standalone file for more easy to maintain, you can see it #4404, also apply the solution you provided.
> 
> but we still fixing some unexpected issues.
Hi,

I have sent a PR to the mentioned branch to address this issue. If there are any other problems or if I can assist further, please let me know.

Thank you!

**Comment by 2nthony** [comment]
the useEffect dependencies should never use any DOM object, so we're creating a new PR to handle this.
