### ISSUE TITLE
Show voting TODO list

### ISSUE THREAD

**Issue by ggwpez** [opensquare-network/subsquare#4407]
Hey guys, thanks for the awesome Subsquare UI ❤️   

I like using it, but sometimes it can be difficult which proposal i did not yet vote on. Proposals in the fellowship pass faster when they have more votes, so what i would wish for would be a TODO list for members.  
That TODO list could show all proposals that i did not yet vote on but am permissioned to do. Maybe for higher ranks even something like "You still have x days to retain this candidate, otherwise they will be possibly demoted".  

WDYT? Is just creating issues in this repo fine or is there another way here?

**Comment by wliyongfeng** [comment]
Hey @ggwpez , thanks for reaching out. Yeah, this repo is the best way for bugs, improvements or feature request. You can also reach us in our [element group](https://app.element.io/#/room/#opensquare:matrix.org). We have an issue #4288 which list our plan for collectives milestone 2. We have plans to add some warnings like "x days remaining to retain".

Other users also proposed to implement a un-voted referenda list. We will leverage the priority of this issue.

**Comment by wliyongfeng** [comment]
@ggwpez We've implemented a referenda filter to show voting todo. Try it https://collectives.subsquare.io/fellowship.

![img_v3_02d4_e6629bba-8e69-4f55-a818-fabbf0d2981g](https://github.com/user-attachments/assets/62a48caf-5383-4e15-8b94-9223ffac1490)

**Comment by ggwpez** [comment]
Thats cool, many thanks! It shows nothing, since i always vote on everything but once something comes up i will try it again.
