### ISSUE TITLE
Disable vote button and show warning info for member who are unauthorised to vote

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4419]
![image](https://github.com/user-attachments/assets/8ec544e4-e527-4d98-ba8b-b56a4936a6d7)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20606-14834&t=8yQTRpihEUSGBe7T-11)

- Disable the vote button if the user is unauthorised to vote
- Show the description in the tooltip when hover over the disabled button: Only members with rank >= {required rank} can vote

Preview
<img width="320" alt="image" src="https://github.com/user-attachments/assets/9284b3cc-665d-4e24-9693-82590bfe3c87">
