### ISSUE TITLE
Display NFT on AssetHub

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4448]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=21120-20622&t=iJuc4FFXqPgcz3nj-11)

- Add `Assets` and `NFTs` tab to Assethub overview page
- Display the NFTs owned by the address
   - image
   - name
   - collection

Preview
<img width="320" alt="image" src="https://github.com/user-attachments/assets/19f8082a-d7a2-4f50-b53f-88f2e13221aa">

---

- Similarly, display the NFTs owned by the address on user profile page

Preview
<img width="320" alt="image" src="https://github.com/user-attachments/assets/282f1d50-c417-4abb-bfa0-4d88d76daa22">

**Comment by wliyongfeng** [comment]
I added this task to backup issue #2495.
