### ISSUE TITLE
Polkagate Snap wallet button issues

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#4455]
- In Nova app, press the snap button throws an error: `invalid json request`
- in Metamask app, throws error: `wallet_requestSnaps does not exist / is not available`
- in Subwallet app, throws error, the first error is `not authorized`, and then always same as metamask app

**Comment by 2nthony** [comment]
@AMIRKHANEF hi, we just found out these issues, any ideas to fix?

**Comment by AMIRKHANEF** [comment]
hi, thanks for reaching out, about 

> @AMIRKHANEF hi, we just found out these issues, any ideas to fix?

Hi @2nthony,

Thank you for bringing these issues to my attention.

Metamask does not support Snaps on Metamask Mobile yet. Therefore, we need to disable the Snap option.

**Comment by AMIRKHANEF** [comment]
As a suggestion, this function addresses the issue by determining if the user is on a mobile device:

```
// Returns true if the user is on a mobile device based on the user agent string.
const isOnMobileDevice = () => {
  return /Mobi|Android|iPhone|iPad|iPod|Tablet|BlackBerry|Opera Mini|IEMobile|WPDesktop|Mobile/i.test(navigator.userAgent);
};
```
