### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by kianenigma** [opensquare-network/subsquare#4456]
It would be great to provide an RSS feed around all openGov related activity.

**Comment by wliyongfeng** [comment]
Hmm..., we'll think about it, thanks. Before that I think you can try email or telegram notifications.

**Comment by kianenigma** [comment]
> can try email or telegram notifications.


links please?

**Comment by wliyongfeng** [comment]
> links please?

Connect your address first, and then go to [notification settings page](https://polkadot.subsquare.io/settings/notifications). Let me know if any further problems.

**Comment by kianenigma** [comment]
Thanks
