### ISSUE TITLE
connect `polkadot extension` issue

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#4460]
solution for this:

- [x] wait for 10 seconds, if timeout, display an error text under the `AddressSelect`
the text is: `Request timeout, refresh the page` OR better one

<img width="561" alt="image" src="https://github.com/user-attachments/assets/c3d6ed5e-a7f9-4ddc-9f48-8cff40273f28">

---

when this error appear, click polkadot.js no response

<img width="928" alt="image" src="https://github.com/user-attachments/assets/cb32246b-daa9-4fb3-9e99-7550106bc1ad">

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=21258-9506&t=KkIsDWxdyWLDxPwh-11)

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/fd9d3c3c-6547-4aaa-ac90-2341776af010">

**Comment by wliyongfeng** [comment]
Error message: "The wallet request timed out. Please refresh the page and try again later." @2nthony @Popoulosss
