### ISSUE TITLE
Enhance `valid_from` UI on USDx spend proposal

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4579]
1. Set the default state to be disabled, and the final value will be `None`(mostly used).
2. Users can click an icon to set a block height so they can set `valid_from` for a future spend, for example milestone based spends.

![image](https://github.com/user-attachments/assets/698be426-bf9a-485d-9c14-5e0b39b7a3a0)

@Popoulosss CN: 这个输入框有disabled和可编辑两种状态。如果是disabled状态，最终提交的时候，`valid_from`的值将会为`None`；如果是可编辑状态，那么用户可以输入一个块高最为值，如果这个值合法，那么最终用这个值提交，如果用户没有输入，则提交的值为`None`。

**Comment by Popoulosss** [comment]
- Change the text `Blocks` to `Block Height`
- The `Valid From` input
