### ISSUE TITLE
[BUG] broken HTML table within Markdown

### ISSUE THREAD

**Issue by tien** [opensquare-network/subsquare#4580]
Subsquare was unable to correctly render the table in this proposal: https://polkadot.subsquare.io/referenda/1099

![image](https://github.com/user-attachments/assets/bcb6bcf6-4362-4f86-ae9f-725d0e27b7d5)

The same in Polkassembly was rendered correctly: https://polkadot.polkassembly.io/referenda/1099

![Screen Shot 2024-08-18 at 22 53 19](https://github.com/user-attachments/assets/fc84ef48-3f6a-4423-9083-4baf4feb190d)

**Comment by tien** [comment]
Hey, thanks so much for getting this fixed so quickly as per usual :D

I've got a different issue now: I'm trying to update my comment to say that it's fixed, but there appear to be no options to do so

<img width="777" alt="image" src="https://github.com/user-attachments/assets/bf4206b0-cae4-4514-ba49-e6a5570f6bb0">

**Comment by wliyongfeng** [comment]
> I've got a different issue now: I'm trying to update my comment to say that it's fixed, but there appear to be no options to do so

@tien We've implemented [sima-spec](https://github.com/opensquare-network/sima-spec/blob/main/governance/v1/README.md) for governance context and discussions. You can not edit a previous comment so we can keep all history, but you can append new comments.

**Comment by tien** [comment]
Alright, thanks for the clarification! This is subjective, but it could be beneficial to have maybe a grayed out edit button, that contain a tooltip explaining this. Else, what might happen is: users could think that this is a bug and go to another platform instead. This is just my personal feedback of course :D

**Comment by wliyongfeng** [comment]
Yeah, thanks for the suggestion.
