### ISSUE TITLE
Changing the vote doesn't work

### ISSUE THREAD

**Issue by bkchr** [opensquare-network/subsquare#4601]
I first voted `Nay` and now want to switch to `Aye`. The voting popups is showing the buttons, but pressing these buttons doesn't work.

![image](https://github.com/user-attachments/assets/7264e343-56e3-40eb-8a93-6158a6f5a72c)

The console is showing the following errors(same error for both buttons):
![image](https://github.com/user-attachments/assets/bfd98bda-fb3f-4fb5-8dc3-1233416c05aa)

**Comment by bkchr** [comment]
Just realized that voting in general is broken? Also voting on another referendum (I didn't voted on before), doesn't work.

**Comment by wliyongfeng** [comment]
Fixed. Ty!
