### ISSUE TITLE
Show fellowship evidence content directly

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#4607]
- [x] referendum detail
- [x] fellowship core member card
- [x] user page evidence card

**Comment by Popoulosss** [comment]
User page evidence card

[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20917-133738&t=ED5LUtVnXjntkZv4-11)

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/91a8dc9c-a61e-4f37-97d0-de1e79ff823e">
