### ISSUE TITLE
Separate native asset(dot) from assets

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4613]
We may show a separated panel for native asset on assethub chain.

![img_v3_02e5_aeb30e29-d9e0-40ca-86d3-68de045693fg](https://github.com/user-attachments/assets/98b7398a-9b72-4676-8899-32012eee36d8)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=20706-42299&t=ED5LUtVnXjntkZv4-11)

Preview
<img width="320" alt="image" src="https://github.com/user-attachments/assets/8d3da332-cf9a-4af5-9868-09ba03246f6a">
