### ISSUE TITLE
Creating a Fellowship referendum leads to a 404

### ISSUE THREAD

**Issue by bkchr** [opensquare-network/subsquare#4614]
I used the UI to create a referendum and then it redirected me to an non existing page.

![image](https://github.com/user-attachments/assets/982d8f21-e66a-4788-ad15-b5216c0bc306)

It should redirect to https://collectives.subsquare.io/fellowship/referenda/195 and not https://collectives.subsquare.io/fellowship/195

**Comment by wliyongfeng** [comment]
Fixed. I'm looking into the decision deposit issue.
