### ISSUE TITLE
Fellowship referenda title mentions wrong rank

### ISSUE THREAD

**Issue by ggwpez** [opensquare-network/subsquare#4615]
I opened a [promote referenda](https://collectives.subsquare.io/fellowship/referenda/187) to rank 1 member and the title mentioned rank 2:

![Screenshot 2024-08-16 at 20 17 55](https://github.com/user-attachments/assets/3fca060d-db14-4a79-bec3-70e2613f1baa)

**Comment by wliyongfeng** [comment]
Thanks. I fixed it in subsquare scan scripts. Let me know if there are still issues.
