### ISSUE TITLE
Support creating proposals for collective members

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4624]
- Council
- T.C.
- Astar community council

**Comment by wliyongfeng** [comment]
For astar/shibuya community council: @Popoulosss 

1. First show a list of templates
2. Templates include `Approve a treasury proposal`, `Common`. There will be a dApp staking related template soon.
3. When `Common` template is clicked, show fields include `threshold` and `proposal`.
4. When `Approve a treasury proposal` is clicked, show fields include `proposal id`(select, we need load all active proposal ids from on chain).

**Comment by 2nthony** [comment]
## council promote motion

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/42bc634b-8c72-47fe-857e-9d62f23adcd8">
