### ISSUE TITLE
Optimize the display of the exceeded decision period

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4664]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=23554-151909&node-type=FRAME&t=fBt8yuolEqdteJGn-11)

- If a referendum is in the confirmation but the decision period has ended, the decision will continue until the end of the confirmation period. Because the decision period has currently ended, and the referendum will be rejected once the confirmation stops.
- When the total period is exceed the decision period
   - show a scale of decision period(right-aligned)
   - show the total period in tooltip when hover over the prograss bar
   - add a prompt to explain the referendum will be rejected once the confirmation stops

<img width="640" alt="image" src="https://github.com/user-attachments/assets/60de7452-e503-4796-b5e8-e48435a71744">

**Comment by wliyongfeng** [comment]
- Only show the mark when `current decision time + confirmation time > track decision time`.
- Show warning text when decision time is over track decision time.
- Show how much time left in the normal decision time
