### ISSUE TITLE
Add claim button on bounty detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4667]
We have claim button on child bounty detail page. We should also support it on bounty detail page.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=23595-149869&node-type=FRAME&t=VfwIAyPATSov8xpo-11)

- Add a `Claim` button below the `Balance` side panel to bounty detail page when the bounty is funded

<img width="320" alt="image" src="https://github.com/user-attachments/assets/c3c04574-00db-4de1-9550-e7c14deb6a0f">

---

- Add the icons to the `Balance` side panel

<img width="320" alt="image" src="https://github.com/user-attachments/assets/14c7e9f6-7c3d-46aa-a6c9-643bd42e28b9">

---

- Change padding left value signatories list to 0.625rem or 10px

<img width="320" alt="image" src="https://github.com/user-attachments/assets/caffb60c-eee6-4b49-9379-d365172b12da">
