### ISSUE TITLE
Fellowship treasury spends on Collectives chain

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/subsquare#4679]
- fellowship referendum <-> treasury spends
- Show spends info on fellowship referendum detail page

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=23605-3678&node-type=FRAME&t=VfwIAyPATSov8xpo-11)

<img width="640" alt="image" src="https://github.com/user-attachments/assets/e2c7f50c-c096-4d27-a200-22b9cb242001">

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=23605-3678&node-type=FRAME&t=VfwIAyPATSov8xpo-11)

- Add `Treasury Spends Stats` Panel on overview page

<img width="320" alt="image" src="https://github.com/user-attachments/assets/2a7266cd-66a7-4b36-bc6e-e2d03524e932">
