### ISSUE TITLE
Show assethub treasury assets on polkadot overview page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4686]
Currently we only show assets on relay chain, but we should also show assets on assethub.

Assets on assethub:

- [ ] For fellowship assets, currently only dot, check address [16VcQSRcMFy6ZHVjBvosKmo7FKqTb8ZATChDYo8ibutzLnos](https://statemint.statescan.io/#/accounts/16VcQSRcMFy6ZHVjBvosKmo7FKqTb8ZATChDYo8ibutzLnos).
- [ ] Normal treasury, for common purpose, assets including USDC, USDt, DOT, address [14xmwinmCEz6oRrFdczHKqHgWNMiCysE2KrA4jXXAAM1Eogk](https://statemint.statescan.io/#/accounts/14xmwinmCEz6oRrFdczHKqHgWNMiCysE2KrA4jXXAAM1Eogk)

![img_v3_02ei_317211d5-8a39-4c51-b6a8-0339f03ed77g](https://github.com/user-attachments/assets/a736ce09-7105-465c-add3-e4c177d46e5a)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=23616-12974&node-type=FRAME&t=529xq8bVIP4IHvUj-11)

- Show the total treasury(fiat money)
- Show relay chain treasury and stats
   - treasury(dot and fiat money)
   - to be reward(dot and fiat money)
   - next burn(dot)
   - spend period
- Show multi assets treasury(assethub) and the amount of each asset, click the subtitle link to the [statescan](https://statemint.statescan.io/#/accounts/14xmwinmCEz6oRrFdczHKqHgWNMiCysE2KrA4jXXAAM1Eogk)
- Show fellowship treasury(assethub)(dot and fiat money), click the subtitle link to the [statescan](https://statemint.statescan.io/#/accounts/16VcQSRcMFy6ZHVjBvosKmo7FKqTb8ZATChDYo8ibutzLnos)

<img width="640" alt="image" src="https://github.com/user-attachments/assets/c6bcb767-f5c6-401a-83d5-bef1f8f0db43">
