### ISSUE TITLE
Add new proposal template on Collective to spend DOT on AssetHub

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/subsquare#4697]
Add new proposal template on Collective to spend DOT on AssetHub

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=23836-13031&node-type=frame&t=lypi60V0pDQO8NNR-11)
