### ISSUE TITLE
Show requesting amount, ongoing/all treasury proposal numbers for fellowship

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4710]
![img_v3_02em_4de51c6e-df1e-4eab-86f6-79bf7bc0dbag](https://github.com/user-attachments/assets/5cfaf79f-7e7d-4e7f-877a-bc92ca620fc5)

Currently we only have available balance and `to be awarded`.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=24035-13988&node-type=frame&t=FCWmjIb8FM4nszQA-11)

- Add `Requesting Amount` data: DOT amount and fiat currency
- Add `Treasury Proposals` data: active / total
   - When hover over the number of active proposals, show `Active Proposals`
   - Click the the number of active proposals, link to the Fellowship treasury spends page

<img width="640" alt="image" src="https://github.com/user-attachments/assets/0eb387a9-43ea-47ae-a075-ddfca2f481ec">
