### ISSUE TITLE
Kusama Ref description is wrong

### ISSUE THREAD

**Issue by ggwpez** [opensquare-network/subsquare#4761]
This Ref https://kusama.subsquare.io/referenda/173 does have a title and description of another Ref. I  never wrote this text:

![Screenshot 2024-09-24 at 12 45 43](https://github.com/user-attachments/assets/0160e708-bcaf-43cc-b4a0-40c40552ddb2)

I was never able to edit the text and instead posted the context as a comment:

![Screenshot 2024-09-24 at 12 45 52](https://github.com/user-attachments/assets/758c89d4-7897-40b6-9a90-dec5d0a3bd7d)

You can see on Polkassembly that it is indeed empty:

![Screenshot 2024-09-24 at 12 46 19](https://github.com/user-attachments/assets/c22cb048-3663-4f04-b62c-1c4aca33c915)

I just noticed that when clicking on my account and seeing this unknown proposal title 😆

**Comment by wliyongfeng** [comment]
Weird, we synced this context from Polkassembly's API. Will check it soon. Thanks.

**Comment by wliyongfeng** [comment]
I think it's the same issue we had before with Polkassembly's API. It return context for wrong network. For this referendum, it's [referendum #173](https://polkadot.subsquare.io/referenda/173) of polkadot.

**Comment by wliyongfeng** [comment]
https://kusama.polkassembly.io/api/v1/posts/on-chain-post?postId=173&proposalType=referendums_v2

Header:
x-network:  kusama

![img_v3_02f2_0dd23101-1b72-4d7d-9f0b-c5b01e1e551g](https://github.com/user-attachments/assets/7bf2cc64-f399-4329-875a-38df288522bb)

We are in contact with PA team to get feedbacks.

**Comment by ggwpez** [comment]
Thanks for the quick fix!
