### ISSUE TITLE
Show polkadot general treasury status panel on proposal summary

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4797]
![img_v3_02f4_006c39ff-425b-4694-b5ea-161b16bfebcg](https://github.com/user-attachments/assets/8a46def6-8d92-42af-a417-3e4b21103da1)

Take place of following section

![img_v3_02f4_40fad388-50c3-4caa-adea-2d1055f75deg](https://github.com/user-attachments/assets/5cc5b1e7-79d5-48d4-a683-5167895ae6ce)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=24787-24454&node-type=frame&t=RVBFFgu4vEXdEqJ4-11)

<img width="640" alt="image" src="https://github.com/user-attachments/assets/2f798c72-8306-4b1f-8e48-0b628f811061">
