### ISSUE TITLE
As a user, I want to filter out all treasury request referenda

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4807]
So I can see treasury requesting status.

Work:

- [x] Add treasury related field in scan scripts @wliyongfeng 
- [x] Add API for treasury related referenda. This API will also be used by [dotreasury](https://polkadot.dotreasury.com/) applications page.
- [x] Fronted components.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=24989-14206&node-type=frame&t=66T0jYImMVDCurF5-11)
