### ISSUE TITLE
Error when submitting vote on any referenda

### ISSUE THREAD

**Issue by AMIRKHANEF** [opensquare-network/subsquare#4831]
When attempting to submit my vote on any referenda on Polkadot, I encounter an error regardless of the wallet used. The error appears consistently, but does not prevent me from completing the voting process. (maybe there is something wrong on my side, not sure!)

**Steps to Reproduce:**
1. Go to any referenda on SubSquare.
2. Attempt to submit a vote.
3. Observe the error (occurs with any wallet).

![image](https://github.com/user-attachments/assets/97d979e3-675d-40ff-8bbe-aee9b2917d45)

**Comment by wliyongfeng** [comment]
And could you try vote in chrome incognito mode?

**Comment by AMIRKHANEF** [comment]
Everything's working great in incognito mode!
But for some reason, after refreshing the tab in regular mode, the error comes back.
Sorry for the trouble—this might just be something on my end, so I'll look into it more and keep you updated!

**Comment by AMIRKHANEF** [comment]
I’m closing this issue because it seems to be a problem specific to my setup on Chrome. Everything works perfectly fine on Firefox. Additionally, this issue isn’t isolated to Subsquare; I’ve noticed similar errors on other websites developed with Next.js, such as CoinMarketCap. I’ll continue investigating on my end, but for now, it appears to be Chrome-specific.

**Comment by wliyongfeng** [comment]
Thanks and LMK if we can provide any help.
