### ISSUE TITLE
Add filter on profile votes page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4877]
So we can filter votes by Aye, Nay or Abstain
![img_v3_02fl_7580923c-0bab-4016-ae32-3ebe62fde68g](https://github.com/user-attachments/assets/8e23d7f3-26ae-42b8-a8a0-821324a2f4f6)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=25415-151602&node-type=frame&t=66T0jYImMVDCurF5-11)
