### ISSUE TITLE
As a user, I want to see AI summary of a proposal on list pages

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4951]
- An icon on proposal card for AI summary on list pages
- Show AI summary when hovering on this icon

@Popoulosss We need your design.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=26333-2403&node-type=frame&t=uGr3XkjBkZMBfBCP-11)

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/e5915d93-83f2-4162-b48b-b1c742e984a2">
