### ISSUE TITLE
Other assets will disappear after one asset is transferred on assethub

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#5073]
I transfer some amount of USDT from assethub and I also have other assets. After my transfer of USDT, other assets disappeared after my transfer.

**Comment by Demilewis** [comment]
> I transfer some amount of USDT from assethub and I also have other assets. After my transfer of USDT, other assets disappeared after my transfer.

Hey there @wliyongfeng  !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delay. It looks like you’re dealing with a transcript error—a system glitch causing incorrect or missing communication logs. To resolve this, I recommend contacting the support team for expert guidance.

I’ve already set up a support ticket for you (ID: OPS7638). Please visit [Opensquare Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat bubble at the bottom right to connect with an agent for prompt assistance.

If you need immediate help, the live chat is the fastest way to get support.

Thank you for your patience—I’m confident this will be resolved quickly!
