### ISSUE TITLE
Improve advanced text on some popups

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#5164]
Maybe `open/hide` is better.

![img_v3_02hc_9e7cfcfa-88d3-47bd-8aa4-a49c467ac33g](https://github.com/user-attachments/assets/b055a8c2-8d91-49dc-9422-316684326ab4)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=28450-196424&node-type=section&t=IeQJmzo0EodDjWb7-11)

Preview
<img width="320" alt="image" src="https://github.com/user-attachments/assets/2c7b57fe-3b9d-4b5f-875f-e74da9876356">
