### ISSUE TITLE
[Fellowship] Show demotion status on a referendum to retain a member at his/her rank

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#5189]
So we can know the context.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=28631-239388&node-type=section&t=DF2Fsk9hA2PQp3Sa-11)

Show the member's status card on the right side. Refer to the core member's card, and only show the progress bars for demotion and promotion.

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/373987a1-40e9-4b3d-818b-0b402f26cccb">
