### ISSUE TITLE
[Fellowship] Display a snapshot of eligible voters on the referendum detail

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#5236]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=28746-301006&t=8vQkZj82aayNkouK-11)

- Add a entrance `Eligible Voters` to the tally card
- Implement eligible voters detail dialog

**Comment by anaelleltd** [comment]
Hello team.

Just so you know, the new feature "Eligible voters" tab is doubling up on the existing "All votes" tab, as shown below.
OLD:
![SubsquareUI_Votes1](https://github.com/user-attachments/assets/09665ee6-74b9-4b96-a095-7e76963d601f)

NEW:
![SubsquareUI_Votes2](https://github.com/user-attachments/assets/1fa5289b-71ab-4158-a703-2ed1b06781e6)
 
It might be worth removing the old "All votes" tab to avoid confusing users as to its purpose.
Thanks.

**Comment by wliyongfeng** [comment]
@anaelleltd Thanks for the suggestion. We've removed the old "All votes" interface.
