### ISSUE TITLE
Add ambassador sub section to polkadot treasury

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#5303]
The related treasury spend is [here](https://polkadot.subsquare.io/treasury/spends/77).

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=29715-194473&t=idMnPzjiKFNoig5z-11)

Preview
<img width="640" alt="image" src="https://github.com/user-attachments/assets/0bb4d291-7c89-4d74-ae58-69b3b30a4b89" />
